### ISSUE TITLE
How do I properly set up a PosixFileHandler?

### ISSUE THREAD

**Issue by denodster** [y-lohse/inkjs#1013]
I'm trying to complile in node (Alternatively, is there a way to have webpack run the compiling?)

heres my code running in express:
```
  const inkFile = fs.readFileSync(`${story.path}/main.ink`, 'UTF-8').replace(/^\uFEFF/, '');
  const fileHandler = Inkjs.PosixFileHandler(".")
  const jsonFile = new Inkjs.Compiler(inkFile, {fileHandler}).Compile();
```

I have includes in my ink which is the reason I can't seem to figure out how to get this to work.

Heres my error:
```
(node:24950) UnhandledPromiseRejectionWarning: TypeError: Inkjs.PosixFileHandler is not a function
    at /home/user/project/routes/index.js:132:29
```

I'm running debian linux.

I feel like i'm so close, but I just can't seem to figure out what I'm doing wrong.

Thank you.

**Comment by smwhr** [comment]
Did you require `inkjs-full-posixhandler.js` ? The PosixHandler class is delivered as a separate file from the main inkjs as it uses node-only APIs.

**Comment by denodster** [comment]
I used npm to install the package so I don't have the code in my folder. require('inkjs-full-posixhandler.js') gives me `MODULE_NOT_FOUND` how do I import it correctly?

**Comment by denodster** [comment]
got it:

```
  var Inkjs = require('inkjs');
  var { PosixFileHandler } = require('inkjs/compiler/FileHandler/PosixFileHandler');
  const inkFile = fs.readFileSync(`${story.path}/main.ink`, 'UTF-8').replace(/^\uFEFF/, '');
  const fileHandler = new PosixFileHandler(`${story.path}/`);
  const errorHandler = (message, errorType) => {
    console.log(message + "\n");
  }
  const compiledInk = new Inkjs.Compiler(inkFile, {fileHandler, errorHandler}).Compile();
```

**Comment by smwhr** [comment]
Thanks for the code, I've added it as an example in the docs.
