### ISSUE TITLE
Serverless template Uncaught Error: Failed to convert token to runtime object: "#", but working with ink-full.js

### ISSUE THREAD

**Issue by JeFawk** [y-lohse/inkjs#1017]
## Describe the bug
Using the browser_serverless template, I added a json file exported from ink with tags (you use # in ink to make them) but ran into this error:
Failed to convert token to runtime object: "#"

Once I used this js file, it got fixed: https://unpkg.com/inkjs@2.2.1/dist/ink-full.js

## Environment
 - OS: macOS
 - Node.js version: 
 - Web browser version: 
 - _inklecate_ version: 
 - _inkjs_ version:

**Comment by smwhr** [comment]
Oh, i may have forgotten to update the templates with the latest version. We should automate that.

You should not have to use inkjs-full if you're not doing any compilatiom. To read a json exported from inky the base inkjs is enough (and smaller)

**Comment by JeFawk** [comment]
> Oh, i may have forgotten to update the templates with the latest version. We should automate that.
> 
> You should not have to use inkjs-full if you're not doing any compilatiom. To read a json exported from inky the base inkjs is enough (and smaller)

Can you please point out where the base inkjs would be located? I haven't managed to find it (inkjs in js, not ts)

Thank you

**Comment by smwhr** [comment]
It's available to download in the [release section](https://github.com/y-lohse/inkjs/releases), or you can use npm or yarn.

It's also available on all major CDNs like [jsDeliver](https://www.jsdelivr.com/package/npm/inkjs?tab=files) or [unpkg](https://www.unpkg.com/inkjs@2.2.1/dist/ink.js)

**Comment by smwhr** [comment]
(The files in the `templates` folder have been updated)
