### ISSUE TITLE
export `JsonSerialisation`

### ISSUE THREAD

**Issue by LarchLiu** [y-lohse/inkjs#1040]
In some cases, i want to parse some objects from `json file` such as `global decl`, so that i can get all the variable names that defined in the `ink`. And i want to get all the `KNOTS`, `DIVERTS`, `CHOICES` before start game.

So could we export the `JsonSerialisation` to allow users to utilize it directly in their own code?

**Comment by smwhr** [comment]
From 2.2.5 onward, you will be able to use `import { JsonSerialisation } from 'inkjs/engine/JsonSerialisation';`
