### ISSUE TITLE
Option to initialize the story with already parsed JSON

### ISSUE THREAD

**Issue by Oreolek** [y-lohse/inkjs#12]
Here's the thing: `fetch()` doesn't work in older browsers, and jQuery's AJAX functions parse JSONs automatically. But inkjs can't work with already parsed JSON objects.

**Comment by y-lohse** [comment]
Hello, 
version 0.9.0 should accept a JSON object as well as a string. I'll close this issue, feel free to re-open it if doesn't actually work!
On older versions, you can always use `JSON.stringify()` before creating the story.
