### ISSUE TITLE
[Question]: Are you planning to upgrade to new 0.8.0 version of Ink?

### ISSUE THREAD

**Issue by fireton** [y-lohse/inkjs#126]
Just wondering. I'm working on a small ink game and choosing a platform to implement it.

**Comment by Tom-Julux** [comment]
Most of the improvements in Version 0.8 are on the compiler side. You can use the current inkjs version with the ink 0.8 compiler in most cases. However you have to change the version of your json file manualy.

from
```json
{"inkVersion":18}
```
to 
```json
{"inkVersion":17}
```

Then everything should work as expected

**Comment by erkyrath** [comment]
In that case, it's worth updating inkVersionCurrent to 18.

**Comment by joethephish** [comment]
While @Tom-Julux's little hack may work in many cases, there's a good reason I bumped the version number - the story format has changed slightly. So while it might work for your story, I'd say you should only do so at your own risk! At a guess though, the main errors you're likely to see are to do with newline handling, which may not be the end of the world for most people.

**Comment by joningold** [comment]
We recommend you use inky; the current build will let you work on latest ink for Unity, with the export to web option falling back to the older version of ink-js. There are few unsupported features / changes, but at least it's less confusing.

**Comment by y-lohse** [comment]
Hi all! Sorry for the delay, I was offline for a while. But now that I'm back, yes, I certainly plan on updating inkjs. Help is of course always appreciated, but I haven't looked into what needs to be done yet. I'll create a work in progress PR soon-ish.
