### ISSUE TITLE
Add InkList to module's public exports

### ISSUE THREAD

**Issue by joethephish** [y-lohse/inkjs#136]
Currently it doesn't seem to be possible to construct an InkList e.g. with `var myList = new inkjs.InkList()`, in order for the game to pass something into the engine.

Would it be possible to open this up? I'd submit a pull request, but I'm afraid I'm not sure how the build system works...!

**Comment by y-lohse** [comment]
Yeah it should be possible! I don't have time to test it right now, but in theory you just import `InkList` in `Story.js`, and the `export InkList` in there somewhere.
For example, [this is where `Story` is exported](https://github.com/y-lohse/inkjs/blob/master/engine/Story.js#L28).

**Comment by joethephish** [comment]
Hrm, I tried a few things but couldn't get it to work I'm afraid! I'm a bit out of my depth with the way new JS + Babel and stuff works. Does Babel maybe expect there to just be one thing exported?

**Comment by y-lohse** [comment]
Mmh no exporting multiple modules should be fine. Are there any error messages? Or just no `InkList`?

I'll have a look at it on my next inkjs session otherwise :)

**Comment by y-lohse** [comment]
Mmh ok, that's what I had in mind too, must be something else going on then. I'll have a look at it!
