### ISSUE TITLE
Add test for list shuffling

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#147]
After #145, it'd be good to have a test case covering that. Testing randomness can't be difficult, can it?

**Comment by ephread** [comment]
@y-lohse I believe this one can be closed. There's now tests covering shuffles ([here](https://github.com/y-lohse/inkjs/blob/8e4f2a2e6ca4f3bff7c4c6c3bb59728164590a43/src/tests/specs/ink/Sequence.spec.ts#L38) and [there](https://github.com/y-lohse/inkjs/blob/8e4f2a2e6ca4f3bff7c4c6c3bb59728164590a43/src/tests/specs/ink/Sequence.spec.ts#L46) for instance).

**Comment by y-lohse** [comment]
👍 thanks!
