### ISSUE TITLE
Reversed output stream

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#17]
```
-> start

=== function get_stalk_time ===
{
- time == 0:
	~ return "12 AM."
- time < 12:
	~ return "{time} AM"
- time == 12:
	~ return "12 PM."
- else:
	~ return "{time - 12} PM"
}

=== start
VAR time = 11
{ get_stalk_time() }
-> END
```

The following example should produce `11 AM`, but produces ` AM11` instead. The problem starts [around here](https://github.com/y-lohse/inkjs/blob/master/engine/Story.js#L644).

Ping @pineapplemachine who found this one.

**Comment by y-lohse** [comment]
@pineapplemachine Is it possible you made other changes to the source (apart from 854d29dc5bebd606c00509b2156b5663312327fc) that would have fixed this?

**Comment by pineapplemachine** [comment]
It was a one-line change and I made an error duplicating the change in the repo

**Comment by y-lohse** [comment]
Ah, I see. However, I believe 6c57691852b5a62e7dcc6e9aa3ae624b5b26f860 just fixes the symptom. The [reference code](https://github.com/inkle/ink/blob/master/ink-engine-runtime/Story.cs#L791) doesn't invert things, so there's probably a mistake somewhere else. I'll look into it.

**Comment by y-lohse** [comment]
Here's a smaller test file for reference.

```
=== start
{ get_stalk_time() }
-> END

=== function get_stalk_time ===
~ temp time = 11
~ return "before {time} after"
```

**Comment by pineapplemachine** [comment]
I suspect the example can be further shortened:

``` ink
=== start
before {some|sequence} after
```

**Comment by joethephish** [comment]
Actually, I think it's specific to the string building code? This might be
the simplest repro (also untested!)

`{"before {1} after"}`

**Comment by y-lohse** [comment]
Sort of, your code uses a Stack and mine a simple array, so I was missing last in, first out behavior :|

**Comment by joethephish** [comment]
Cool, good catch!
