### ISSUE TITLE
Add a LICENSE file?

### ISSUE THREAD

**Issue by mattb** [y-lohse/inkjs#19]
I don't see a LICENSE file on the repository. Would it be possible to add one to make the open-source rights clear?

**Comment by erkyrath** [comment]
Ooh, yeah, I should have noticed that when I was doing the Lectrote integration.

The existing Ink tools are MIT license, so that would suit.

**Comment by y-lohse** [comment]
Done 😊
I'm not sure if I really have the right to license the code since its mostly copied from ink, but I guess it's fine.
