### ISSUE TITLE
VariablesState.js: Typescript port considerations

### ISSUE THREAD

**Issue by NQNStudios** [y-lohse/inkjs#192]
@elabraha and I are going through VariablesState.js and VariablesState.cs to assess the best way to port to TypeScript. Here are our notes:

# Stale comment?
I can't tell if these comments need our attention or if they're stale:
at the top of VariablesState.js:
```
//still needs:
// - varchanged events
// - see if the internal getenumarators are needed
```
Lower in the file it looks like events ARE called when variables change (https://github.com/y-lohse/inkjs/blob/6ddf50cb66685e05de11f3a112b4f980e1a90830/src/VariablesState.js#L225). But I'm not sure about `getenumerators`-- has that also been resolved or is this an opportunity to improve on missing functionality while porting?

# Refactor event handling into a class

Variable changed event handlers are [pretty janky right now](https://github.com/y-lohse/inkjs/blob/6ddf50cb66685e05de11f3a112b4f980e1a90830/src/VariablesState.js#L85) in order to emulate C#'s built-in event handlers. I'm not sure if similar event handling happens elsewhere in the code, but it might be worthwhile to refactor this functionality into a CallbackHandler class so it doesn't need to clutter up `VariablesState` and any other place where callbacks need to be registered.

# Direct [] access: 
[Here](https://github.com/y-lohse/inkjs/blob/6ddf50cb66685e05de11f3a112b4f980e1a90830/src/VariablesState.js#L265) a function called `$` has been defined to emulate the way `VariablesState.cs` overloads the `[]` operator [here](https://github.com/y-lohse/inkjs/blob/6ddf50cb66685e05de11f3a112b4f980e1a90830/src/VariablesState.js#L265). In typescript, it's possible to overload `[]` functionality for dictionary-style indexing, so I'd like to propose changing the API to allow this. Maybe, to preserve compatibility with existing inkjs projects, `$` could remain as an alias for the `[]` operator, or vice-versa.

--- 
P.S. let me know if these should be separate issues, or if I should open a WIP pull request instead. Just wanted to get it all documented, but not sure the best way to organize that (pretty new to open source contributing!)

**Comment by y-lohse** [comment]
### Comments

Yep, those are stale and should be removed. No clue what `getenumarators ` refers to but it looks like it wasn't needed after all.

### Event handling

This is the only place where callbacks are used! I'm not sure I understand how you'd want to refactor that part, would you mind going into more detail about what you have in mind? Anyway, I'm open to changing it, but if the change is too big I'd rather it gets done after the initial port.

### Direct [] access

Yep, that sounds good! Would you mind pointing me to the documentation on how to overload `[]`? I have a hard time finding stuff in the official docs.
I think `$` should be the alias, and we'd add a deprecation notice somewhere before removing it entirely.

**Comment by NQNStudios** [comment]
# Event Handling
I've slightly modified the way event handling is done, but since this is the only place in the code where it's needed, I don't think an EventHandler class will be needed.

# Direct [] access
I had misunderstood the TypeScript feature of index signatures: [here](https://basarat.gitbooks.io/typescript/docs/types/index-signatures.html). In fact, the existing solution using ES6 proxies (which I wasn't aware of when I initially suggested a TypeScript solution) is as close as I think we can get.

Closing!
