### ISSUE TITLE
Line break errors in ink-js.1.7.1

### ISSUE THREAD

**Issue by joningold** [y-lohse/inkjs#200]
Using the new build of inky, which integrates the new build of ink-js (so that's Inky version: 0.9.3 -- ink version: 0.8.2 --  inkjs version: 1.7.1  ) the following ink script:

```
~ text() 

== function text() 
    Say what 
    Say who 
    Say where
```
gives me the following in inky:

```
Say what

Say who

Say where
```

and the following ink ink-js:

`Say whatSay whoSay where`

This is likely to be a porting bug of the line break changes introduced in ink-0.8.1

**Comment by joethephish** [comment]
(Note: I removed the new release of Inky for this reason.)

**Comment by joethephish** [comment]
Submitted a pull request for this: https://github.com/y-lohse/inkjs/pull/201

**Comment by joningold** [comment]
Got another one!

```
red {blue_green()}
    
=== function blue_green()
    blue <> 
    green
```

In c# produces `red blue green`. 

In JS, produces 

```
red blue 
green
```

**Comment by joningold** [comment]
Reduced further

```
red <> yellow <> 
green
```

...produces the same issue (the second glue is lost in JS)

**Comment by joningold** [comment]
Reduced further, it's a good one.

```
one <>
two 

```
works but
```
one <> 
two 
```
doesn't. The difference being a single whitespace character to the right of the <> glue

**Comment by y-lohse** [comment]
@joningold is the

**Comment by joningold** [comment]
Apologies; I was unclear. This is a new bug that isn’t fixed by the previous fix

**Comment by joethephish** [comment]
See above pull request - have fixed this second issue: there's a bug in the compiler that's producing empty strings, but inkjs wasn't handling the edge case the same at the C# engine.

**Comment by y-lohse** [comment]
I think they are all fixed now, thanks!
