### ISSUE TITLE
CONST Variables aren't in _inkStory.variablesState

### ISSUE THREAD

**Issue by wolfe7** [y-lohse/inkjs#202]
Not sure if by design, but I did a dump of the entire ink story object and the CONST variables don't show anywhere in it (unless they're part of some of the self referencing stuff I had to not export as JSON.stringify doesn't allow self referential JSON).

I changed the ink variables from CONST to VAR and they show up though.  

I mean accessing like this:

_inkStory.variablesState['myvar'];

if myvar is CONST it is always undefined.  If it's VAR it works.  I don't need to write them, but I do need to read them as the ink developer will set different CONST variables in our game for different stories.  We can use VAR but just reporting this bug as it took me a while to backtrack and figure out what was wrong.

**Comment by joethephish** [comment]
This is as intended I'm afraid. CONSTs are replaced inline with their values at compile time so you can't inspect them at runtime. Will consider changing that though!

**Comment by wolfe7** [comment]
No worries, it just wasn't obvious to me, it'd be nice to be able to read them I suppose but we can do without CONST when we need to read them I think.
