### ISSUE TITLE
Error on ObserveVariable()

### ISSUE THREAD

**Issue by LarskeM** [y-lohse/inkjs#21]
Hi,

registering variable observers like

```
    myStory.ObserveVariable("health", (varName, newValue) => {
        console.log(varName + ' changed to ' + newValue);
    }); 
```

works fine, as long I'am registering observers for every variable which changes its value.

Having 2 variables, but only register a observer for one variable, I get the error:

`Tried to get the value of a variable that isn't a standard type`
from
`Story.VariableStateDidChangeEvent(...)`

Then things get complicated and I'am still trying to figure out, how to load und debug your code unpacked.

Registering multiple observers for one variable works fine again. Thanks for your great work.

**Comment by y-lohse** [comment]
Thanks for the report, i'll look into it when I get a chance.

If you want to run the code unpacked, you'll have to build it with [this line](https://github.com/y-lohse/inkjs/blob/master/Gruntfile.js#L22) commented. I'm really sorry there is no unpacked / unminified version available at this point, I keep meaning to create one.

**Comment by LarskeM** [comment]
Ok. got an unpacked version to run. So many buildtools to learn ;-)

in 
`Story.VariableStateDidChangeEvent(variableName, newValueObj)`

`var observers = this._variableObservers[variableName];`
returns an undefined object, when there is'nt an observer registered for `variableName`
the following if only checks for `newValueObj `
    `if (typeof newValueObj !== 'undefined')`

then
   ```
 observers.forEach(function(observer){
        observer(variableName, val.valueObject);
    });
```
throws an error

checking `observers` fixes the problem in my case

`if ((typeof newValueObj !== 'undefined') && (typeof observers !== 'undefined'))`

**Comment by y-lohse** [comment]
Aaah that's indeed wrong.
 `if (typeof newValueObj !== 'undefined')`
should be 
`if (typeof observers !== 'undefined')`

If you want to submit a PR for this issue I'd be happy to merge it. Otherwise I'll commit the fix later today :-)

**Comment by y-lohse** [comment]
I just published the bugfix everywhere, thanks again for the report and the digging :)
