### ISSUE TITLE
What version of inkle does inkjs support

### ISSUE THREAD

**Issue by axmad22** [y-lohse/inkjs#214]
Tried using your library and loaded a json file created by the editor 

- Inky version: 0.10.0
- ink version: 0.8.2
- inkjs version: 1.7.1 with hotfix

Got Error : 
ERROR Version of ink used to build story was newer than the current version of the engine.

Which IDE of ink do you support ?

**Comment by y-lohse** [comment]
Hi, you can find these infos [in the release notes](https://github.com/y-lohse/inkjs/releases). Right now we're supporting ink v0.8.1, hence the error that you're seeing. Unless you're using features specific to version 0.8.2 you can probably compile your version with ink 0.8.1 and it should work as expected :)

Just curious about

> inkjs version: 1.7.1 with hotfix

what hotfix is that ?

**Comment by joethephish** [comment]
The hotfix is just a hacked version with the fixes I submitted, just so I could kick out a version of inky the same minute instead of waiting for an official inkjs release :)
