### ISSUE TITLE
Ink format 18 is not supported, and no supported version listed in README

### ISSUE THREAD

**Issue by Skrylar** [y-lohse/inkjs#217]
- [X] What is the known-good version of the Ink compiler?
- [ ] Can this be mentioned in the README?
- [ ] I might be able to comb through git and see what the bytecode differences are (provided the known-good version)

**Comment by y-lohse** [comment]
> Can the known-good version of the compiler be mentioned in the README?

It can, but would it help? I mean, what's the workflow that made you end up with a version mismatch?
I'm asking because adding it to the readme means a bit more maintenance, and I'm not sure that a) people would see it and b) people would know what engine version they are using before actually seeing the error.

The last supported version is ink 0.8.1, so all the new stuff from [0.8.2](https://github.com/inkle/ink/releases/tag/0.8.2) can't be used in inkjs yet.

**Comment by Skrylar** [comment]
> what's the workflow that made you end up with a version mismatch?
Personally, I pulled down HEAD from last June (~17 commits before the launch of 0.8.2) and built that. 0.8.1 is around five months back according to the releases tab (https://github.com/inkle/ink/releases) so less industrious users are going to end up with an unsupported version if they just grab the first thing off the list.

> people would know what engine version they are using before actually seeing the error.
this one's a bit weird. when I tried to run a version 18 script it just didn't show anything, but the debug console mentioned the script version was too new. Looking at it now it does not appear that inklecate mentions its own version (https://asciinema.org/a/eAZuC1yMudnQ2kFV6cQX2rRH6). I may have to go bother upstream about versioning.

**Comment by MaxZiebell** [comment]
I was trying Inky for Mac and it offers "Export story.js only" but that JS file can't be read by the serverless demo… so I guess this is releated to this issue?

**Comment by y-lohse** [comment]
Yeah, probably. As the message says, the ink runtime used in the serverless demo is too old compared to the compiler in inky. The latest version of inkjs would work though, you can grab it from npm or from the templates once I've updated them.

**Comment by y-lohse** [comment]
I'm also going to close this issue. With the latest inkjs versions the situation is resolved, at least until the next breaking version of ink. By then hopefully #180 will be in place and the problems will be lesser.

I also don't see any concrete action we could take right now. Manually indicating the compatible version code *somewhere* seems like it would make the release process longer but wouldn't help much. That said if someone sees a way to automate the process I'd be happy to reconsider this :)

**Comment by Skrylar** [comment]
Shell script will do that:
```bash
#!/bin/bash
INK_VERSION=`grep -h 'public inkVersionCurrent =' src/*.ts | head -n1 | sed -e 's/^[^0-9]\+\([0-9]\+\).*$/\1/' -`
```
Which looks for any line which contains `public inkVersionCurrent =` in any typescript file, limits search to the first result, and extracts the first integer on that line and returns it. Depending on the phrasing in the README, `sed` can also be used to update that string too.
