### ISSUE TITLE
v0.8.2 upgrades

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#219]
Here's the diff : https://github.com/inkle/ink/compare/0.8.1...0.8.2#diff-416ce7ac7a3875ac281e55a3e7542022L18

Not too many changes on the engine side, but this will have to wait until the end of #183

**Comment by ephread** [comment]
PR #218 is related to this issue.

**Comment by y-lohse** [comment]
All done, thanks @ephread !
