### ISSUE TITLE
TypeScript definitions?

### ISSUE THREAD

**Issue by isakgrozny** [y-lohse/inkjs#25]
I'm trying to write TypeScript definitions for inkjs, in an attempt to integrate it with a toolset that uses TS, and I'm really not sure where to start. I got as far as `declare var Story;` and got stuck.

Any pointers?

**Comment by y-lohse** [comment]
I might be wrong here, I've never used typescript. 

[Based on this documentation](https://www.typescriptlang.org/docs/handbook/writing-declaration-files.html), the "Single Complex Object in Modules" bit seems like the closest to what inkjs is. if you go down this road, I think you would need to write declarations for the public methods of `Story`.

```
interface Story {
    Continue(): boolean
    etc
}

declare var Story : Story ;

export = Story ;
```

The official ink repo has the documentation for the Story class, in "Running your ink". That looks doable, but I have no clue how the `require` fonction works in TS and how you're supposed to load the actual inkjs .

**Another option** based on [this SO answer](http://stackoverflow.com/questions/27273489/why-doesnt-type-script-support-referencing-javascript-files) is to avoid writting the declaration altogether. 

```
declare var Story: any;
```

That would be enough, but maybe your toolset is a bit more opinionated and really needs the declaration.

Hope it helps :)

**Comment by isakgrozny** [comment]
Thank you, this helped! I got the plug-in working.
