### ISSUE TITLE
funcResult.GetType() doesn't guard against GetType being undefined.

### ISSUE THREAD

**Issue by mwchase** [y-lohse/inkjs#26]
I'm experimenting with external functions, in particular just echoing back input, which has all kinds of confusing behavior currently. (For example, you can get a Path by passing in a divert, but I can't figure out how to send it back. For another example, returning strings is weirdly finicky.)

Many of the issues seem to come from funcResult.GetType(), currently on line 904 of Story.js, throwing an error because funcResult.GetType is not a function. This prevents the warning from being printed, and halts execution.

**Comment by y-lohse** [comment]
Mmmh, yeah, must have skipped that one. I fixed it on the dev branch, but if you have an example of ink file that runs into this error, I could use it to confirm it's ok now.

**Comment by mwchase** [comment]
Here's the code I mentioned. It's currently using an unminified version of the latest iife (so I can get line numbers out of the tracebacks), but switching between them should be fine.
[testing.zip](https://github.com/y-lohse/inkjs/files/481174/testing.zip)
Here's what the output looks like in Inky, using fallbacks that just echo their input:
<img width="580" alt="screen shot 2016-09-19 at 5 37 28 pm" src="https://cloud.githubusercontent.com/assets/882845/18649864/e9961902-7e8f-11e6-9d09-bbf5415b686d.png">

**Comment by y-lohse** [comment]
Great, thank you. I'll have a go with it.

**Comment by y-lohse** [comment]
TBH I don't have time to look at the testing.ink file, but running your html file with the **dev** version of ink produces the same output as inky and no errors, so it should be ok. But feel free to open another issue if you notice a wrong behavior with diverts etc :-)
