### ISSUE TITLE
"previousRandom" field of State not being saved

### ISSUE THREAD

**Issue by joethephish** [y-lohse/inkjs#262]
Only discovered this when i tried to load up a save state in C# that was generated from inkjs.

Here is the serialisation in the C# code:

To JSON:
https://github.com/inkle/ink/blob/7e6b4fe6b3f1834bac8eb73a2de1183674a117be/ink-engine-runtime/StoryState.cs#L361

From JSON:
https://github.com/inkle/ink/blob/7e6b4fe6b3f1834bac8eb73a2de1183674a117be/ink-engine-runtime/StoryState.cs#L402

**Comment by ephread** [comment]
Good catch, it looks like both lines are entirely missing in inkjs:

To JSON:
https://github.com/y-lohse/inkjs/blob/master/src/StoryState.ts#L336

From JSON:
https://github.com/y-lohse/inkjs/blob/master/src/StoryState.ts#L376

@y-lohse do you want me to create a PR with the fix?

**Comment by y-lohse** [comment]
@ephread Sure, if you can that would be awesome!
