### ISSUE TITLE
Serverless example broken

### ISSUE THREAD

**Issue by MaxZiebell** [y-lohse/inkjs#266]
Uncaught Error: Version of ink used to build story is too old to be loaded by this version of the engine
    at new Story (ink.js:6488)
    at main.js:3
    at main.js:91

**Comment by y-lohse** [comment]
Yep sorry, the demo story needs to be recompiled with the latest version of ink. Replace the content with your story and it should work though :)

**Comment by y-lohse** [comment]
I updated the templates, should be all good again.
