### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by aendrew** [y-lohse/inkjs#285]
The latest version on `npm` is `1.8.0-beta.1` whereas [this](https://github.com/y-lohse/inkjs/releases/tag/v1.9.0) seems to indicate v1.9.0 is the latest.

**Comment by y-lohse** [comment]
Oops, it looks like the automatic publication failed. Thanks for letting me know, looking into it!

**Comment by y-lohse** [comment]
Ok, 1.9.0 is published on [npm](https://www.npmjs.com/package/inkjs/v/1.9.0) !

**Comment by aendrew** [comment]
Brilliant, thank you!!! 👍 🙌
