### ISSUE TITLE
EvaluateFunction text output

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#29]
`EvaluateFunction` returns whatever the function returns, but it is also using the `out` keyword to return potential output text. Since there is no `out` in js, I need to find a way around this. 
Note that this requires a StringBuilder class anyway.

**Comment by joethephish** [comment]
If I'd been designing a JS API I guess I'd probably have made it return an object with two fields. Doesn't match the C# API, not sure how important that is though...

Not sure what the alternative is really... a callback function or something I guess.

**Comment by y-lohse** [comment]
Yeah, or maybe an extra parameter `returnTextOutput`, but that's not very elegant either. 
Returning an object is probably the least bad option but then again I don't like muddying the API compatibilities ("It's the same than C#, **except** for this and that").

Hoping for an epiphany before I get to work on it.

**Comment by y-lohse** [comment]
Ok so:

1. `Story.EvaluateFunction(functionName, args)` will return whatever the ink function returns.
2. `Story.EvaluateFunction(functionName, args, true)` will return an object with two properties, `returned` (the value returned by the ink function) and `output` (any text output produced by the function)

There are a couple of alternatives to number 2. We could say that `Story.EvaluateFunction(functionName, args, true)` should return only the text output and not the returned value at all. 
We could also change the signature to `Story.EvaluateFunction(functionName, returnTextOutput, args)` to match the C# version more closely.

If anyone has a strong opinion on this, please let me know ASAP since changing this after the next release would break backwards compatibility :-)

**Comment by joethephish** [comment]
Okay, my 2c: I'd say that we've been pretty lucky so far that it's been possible to keep the exact syntax the same between C# and JS APIs. I'd lean towards using a style that's more familiar to JS devs. Of course it's awkward that you can't *quite* reuse the same docs (unless we put an annotation to mention JS...)

So I think your initial suggestion sounds good! In fact, I even wonder whether (1) is necessary at all, since I'd argue that a native JS framework wouldn't do that.

**Comment by y-lohse** [comment]
> I even wonder whether (1) is necessary at all, since I'd argue that a native JS framework wouldn't do that.

Yeaaah possible, but I think there's value in having a shorthand when you just need the returned value. But thanks, it's merged now! :)
