### ISSUE TITLE
[SUGGESTION] Compress/Base64 encode text

### ISSUE THREAD

**Issue by hlship** [y-lohse/inkjs#292]
From the realm of premature optimizations ...

It feels like you could extract all the text that appears in the game and make one giant string out of it.  Let's call this the text catalog.

The `^` literal text references could identify offsets inside the text catalog, rather than literal text, e.g., `^287,54` to output the substring at position 287 of the text catalog.

The text catalog could be gzip's and Base64 encoded, then decoded on the client side.
I would suspect that the text would compress quite nicely, and have the added benefit of keeping the content of the game obscured.

Possibly, there could be multiple text catalogs, each decoded on first reference.

Pros: Potentially smaller content. May handle larger games better.
Cons: Need to decode the text on first use, decompression library would be needed.

**Comment by y-lohse** [comment]
Hi, thanks for the suggestion!

Note that base64 encoding text actually makes it *larger*, so this would definitely not bring down the size. 
Compressing the catalog would make it smaller of course, but how would we compress it? If we're using gzip… browsers can handle that natively, so the server an just send the gziped JSON, and the external catalog is not needed anymore.
If we're using another compression, any win needs in text size needs to be offset with the size of the decompression library that now ships with ink.js. It'd be interesting to see how big the story text needs to be before we start to save weight.

That being said, it's super unlikely that I would add this to inkjs directly. But having some sort of client-side preprocessor that decompresses the catalog and reconstructs the JSON in memory before feeding it to inkjs should work!

**Comment by y-lohse** [comment]
Feel free to update this issue if you work on something like this, I'd be interested to follow along :)
