### ISSUE TITLE
package.json "main": "dist/ink-es2015.js" breaks old browsers

### ISSUE THREAD

**Issue by safrinafanfei** [y-lohse/inkjs#297]
Hi,

We need to run inkjs in ios 9 browsers, and ink-es2015.js by default is breaking the compatibility.
Can we have "main": "dist/ink.js" instead of dist/ink-es2015.js in package.json? 

Thanks!

**Comment by y-lohse** [comment]
Hello! Sadly not, in order to work on old browsers, `dist/ink.js` ships with a bunch of extra code that is really not needed on most browsers today. But whatever way you load ink in your javascript, you should be abble to load `dist/ink.js` instead of the default main file?
