### ISSUE TITLE
Understanding how story.state.LoadJson(savedJson) works

### ISSUE THREAD

**Issue by evangelinepapanicola** [y-lohse/inkjs#314]
I'm trying to implement save/load functionality in my game using localstorage, but currently calling LoadJson does nothing, and throws no console errors, so I'm a bit lost. If someone could help me understand a bit about how the LoadJson function works, I think I might be able to figure it out. I'm using Vue.js for my game's interface. My code is this:

In the saveState() method:
```
saveState: function() {
      window.localStorage.setItem(localStorageStateKey, this.story.state.ToJson());
}
```
In the mounted function:

```
  mounted: function() {
    this.storyContainer = this.$refs.story;
    fetch("story.json")
      .then(response => {
        return response.json();
      })
      .then(storyContent => {

        this.story = new inkjs.Story(storyContent);

        ink.continueStory(this.story, this.storyContainer);

        window.addEventListener("unload", this.saveState);

        if (this.gameStarted) {
          this.story.state.LoadJson(window.localStorage.getItem(localStorageStateKey));
        }
      });
  }
```
If I refresh to trigger the save, then I check the save in localstorage using chrome devtools, it looks like the save worked just fine:
![image](https://user-images.githubusercontent.com/33719860/57149409-935e6c80-6dc3-11e9-833e-41e9179610b9.png)

But the story still plays from the beginning, instead of loading from the saved point. (Confirmed by console logging out this.story)
![image](https://user-images.githubusercontent.com/33719860/57149875-a3c31700-6dc4-11e9-8f34-f635fb47b3d4.png)

If anyone has any advice, that would be awesome. Thank you :)

**Comment by y-lohse** [comment]
Hi! What does `ink.continueStory(this.story, this.storyContainer);` ? Since it's called before ` this.story.state.LoadJson` that may be the reason why the story starts from the beginning again.

Less likely, but off the top of my head I think `window.localStorage.getItem(localStorageStateKey` will return a string, and `LoadJson ()` may expect JSON. So maybe something like `this.story.state.LoadJson(JSON.parse(window.localStorage.getItem(localStorageStateKey)));`would work better.

Let me know if this helps or if you're still stuck!

**Comment by evangelinepapanicola** [comment]
Thanks so much for responding!

I tried moving `this.story.state.LoadJson` to before `ink.continueStory`, but sadly I got the same result. I also tried using an if/else statement that used LoadJson if a save state existed and `this.story = new inkjs.Story(storyContent)` ... etc if not. Still got the same result.

Finally, I tried `this.story.state.LoadJson(JSON.parse(window.localStorage.getItem(localStorageStateKey)));` just in case getItem was returning a string, but sadly it didn't change anything either. Same result again :(

To give more context to how my code works, the continueStory function is held in a separate libs/ink.js file, exported, and imported into the main Ink.vue file (where the mounted function is). This is as well as importing inkjs from the dependency. I hope I explained that right 😅

**Comment by evangelinepapanicola** [comment]
Ooh, I just noticed if I keep `this.story.state.LoadJson` **after** `ink.continueStory` but JSON.parse the localstorage item like you suggested, I get this console error:
![image](https://user-images.githubusercontent.com/33719860/57287837-3f4bd480-70b0-11e9-81fc-91203f0dcefc.png)

**Comment by evangelinepapanicola** [comment]
After doing some further re-ordering... I think it works now! this seems to work:

```
  mounted: function() {
    this.storyContainer = this.$refs.story;
    fetch("story.json")
      .then(response => {
        return response.json();
      })
      .then(storyContent => {

         this.story = new inkjs.Story(storyContent);

         if (window.localStorage.getItem(localStorageStateKey)) {
          this.story.state.LoadJson(window.localStorage.getItem(localStorageStateKey));
         }

        console.log(this.story);

        ink.continueStory(this.story, this.storyContainer);

        window.addEventListener("unload", this.saveState);

      });
  }
```

I'm pretty sure that's the order you mentioned I should try in the first place, but I must've put the LoadJson line before `this.story = new inkjs.Story` by accident. whoops! Thanks for your help :D

**Comment by evangelinepapanicola** [comment]
What I am having trouble with now, is that if I refresh and trigger save/reload at a choice point, the story doesn't load at all because `story.canContinue = false`. I'm not sure what I can do here to make save load properly...

But at least refreshing at a non-choice point (where `story.canContinue = true`) seems to work and reload the story from that point.

```
  mounted: function() {
    this.storyContainer = this.$refs.story;
    fetch("story.json")
      .then(response => {
        return response.json();
      })
      .then(storyContent => {

         this.story = new inkjs.Story(storyContent);

         if (window.localStorage.getItem(localStorageStateKey)) {
          this.story.state.LoadJson(window.localStorage.getItem(localStorageStateKey));
         }

        console.log(this.story);

        if (this.story.canContinue){
          ink.continueStory(this.story, this.storyContainer);
        }
        window.addEventListener("unload", this.saveState);

      });
  }
```

**Comment by y-lohse** [comment]
Cool, glad you're figured the first issue out!

For the next problem… I actually think everything is fine. You can't `continue` the story at a choice point, but you should be able to present the current choices (using `story.choices` etc). the `if (this.story.canContinue)` makes probably more sense inside `ink.continueStory`, where you can decide if you want to present choices or regular content.

**Comment by evangelinepapanicola** [comment]
Thanks, I'll see what I can do! Looks like I might need to do some more tweaks to `continueStory` - and I'll see if I can figure out displaying the current choices with `story.choices `.

**Comment by evangelinepapanicola** [comment]
All solved! I changed the continueStory function so that on the first iteration `paragraphText = story.currentText` (instead of `paragraphText = story.Continue()`) 🎉

**Comment by katafrakt** [comment]
@y-lohse Sorry to bring this up in a closed issue, but I have a similar problem as the last Evangeline had. I'm loading the game from local storage and it works fine, but I have a problem with displaying text before choices. By using `story.currentText` I can only see text of the last line. And I would like to see whole text since last choice. Is that possible using just inkjs or should I write my own mechanism for it on the side?

**Comment by y-lohse** [comment]
Ah no I'm afraid that's not possible, you'll need to handle that on the side. The previous text isn't even stored in the engine as far as I remember, it only knows about the current state of the story.

**Comment by katafrakt** [comment]
Ok, thanks! I just wanted to make sure I won't reimplement something that is already there :wink:
