### ISSUE TITLE
ObserveVariable not working

### ISSUE THREAD

**Issue by mattrei** [y-lohse/inkjs#329]
Hi,

looking at the tests and the code it really seems that the `ObserveVariable` method is not working. It just does not get emitted when a state variable in the ink engine is changed. 

Also the tests are commented out, that check if a callback has been called by inkjs

https://github.com/y-lohse/inkjs/blob/536eba481b642337335b6540a87e37a3e761502c/tests/specs/IntegrationSpec.js#L42

Is this still a missing feature? It was supported in older versions prior to 1.8.x

**Comment by y-lohse** [comment]
Hi, no it's supposed to work. I can't remember why the tests are commented — I think I couldn't get them to work properly, but that the feature itself was fine. But it's possible they broke recently and we didn't notice because of the commented tests.

**Comment by mattrei** [comment]
They are definitely not working. do you have time to look at it or shall I try my luck on that?

**Comment by y-lohse** [comment]
If you can take a look that would be great! It might be a couple of weeks before I can properly look into it I'm afraid.

**Comment by michael-badrobotgames** [comment]
Just added a PR to fix this FYI

**Comment by y-lohse** [comment]
#343
