### ISSUE TITLE
List creation fails on load in latest

### ISSUE THREAD

**Issue by joningold** [y-lohse/inkjs#339]
The following ink source:

LIST abc = A, B, C 

when exported and loaded via ink-js causes an error as the list definition is built. 

The exact error (in Chrome Version 74.0.3729.169) is 

Uncaught TypeError: Constructor Map requires 'new'

It's hard to unpick the TS / JS code, but it seems to happen in the constructor in ListDefinitionsOrigin.ts.

**Comment by y-lohse** [comment]
Looking at it on discord, but so far I can't reproduce the issue doing this https://codesandbox.io/s/inklistdebug-4rl1d

**Comment by y-lohse** [comment]
The problem happens when using `dist/ink.js`, ie. the legacy browser version. There must be a transpilation problem somewhere I guess.

**Comment by ephread** [comment]
@y-lohse Ouch, I can investigate this over the weekend if you want.

**Comment by y-lohse** [comment]
Let's say that the first one who takes a proper look at it posts here :)

**Comment by ephread** [comment]
It's an issue with Babel. The first thing I'm going to attempt is to migrate to Babel 7, then, I'll report back!

**Comment by ephread** [comment]
Missing configuration setting in the Rollup-Babel middleware, it should be:

```javascript
babel({
    exclude: 'node_modules/**',
    extensions: ['.js', '.ts'],
}),
```

I'll create a PR.
