### ISSUE TITLE
Version 0.9.0

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#355]
Change list here: https://github.com/inkle/ink/compare/0.8.3%E2%80%A60.9.0

Looks like there are a few big ones in there!

**Comment by joethephish** [comment]
Just so you're aware: there's a big feature I added and then subsequently removed called "lookups". Added in 27f3cd7, with modifications added while I was working on other stuff, then eventually fully removed in b8e3547.

**Comment by ephread** [comment]
Let’s get the party started! I’ll create a new branch and a new PR to track the migration (unless you get the chance to do it before me @y-lohse).

**Comment by y-lohse** [comment]
Yep, no problem. Might be a while for me before I have time to do significant contributions, but I'll do my best!

**Comment by y-lohse** [comment]
Yay this is published with v1.11.0 !
