### ISSUE TITLE
Simple story produces no content

### ISSUE THREAD

**Issue by joethephish** [y-lohse/inkjs#36]
The following ink:

```
VAR x = false
{x:
    false
- else:
    true
}
```

...should print `true`. However when inkjs loads the json, it doesn't print anything.

Here is the JSON:

`var storyContent = ﻿{"inkVersion":15,"root":["G>","ev",{"VAR?":"x"},"/ev",[{"->":"4.b","c":true},{"b":["^false","\n",{"->":"6"},null]}],[{"->":"5.b"},{"b":["^true","\n",{"->":"6"},null]}],"nop","G<","\n","done",{"global decl":["ev",0,{"VAR=":"x"},"/ev","end",null],"#f":3}]}`

(ink version 0.6.1, inky version 0.6.0)

**Comment by joethephish** [comment]
(This is causing The Intercept to break, as reported [here](https://github.com/inkle/inky/issues/67#issuecomment-253816697).)

**Comment by y-lohse** [comment]
The sort of bug that makes you wonder how it never bit before. I'm rolling out a new version with the fixes, thanks for the report and boiling down.

**Comment by joethephish** [comment]
It's definitely new - it was preventing The Intercept from working, and it definitely used to work!

**Comment by y-lohse** [comment]
And yet the problem has been there for a long time (the Glue class not extending Object). Is it possible that in the newer versions, the compiled intercept changed so that the first bit of content became a Glue object?

**Comment by joethephish** [comment]
Yeah, that sounds possible. One change I made recently is I made the compiler inline containers where possible, flattening the structure down a lot, simplifying it. So probably the story used to start with a container and now starts with glue.
