### ISSUE TITLE
Tunnels doesn't work..?

### ISSUE THREAD

**Issue by codeartisticninja** [y-lohse/inkjs#37]
The following ink
    -> alpha -> bravo -> charlie -> delta -> END
    
    === alpha ===
    This is alpha.
    ->->
    
    === bravo ===
    This is bravo.
    ->->
    
    === charlie ===
    This is charlie.
    ->->
    
    === delta ===
    This is delta.
    ->->

thows the following err:

    ink.js:942 Uncaught TypeError: Cannot read property 'components' of undefined

**Comment by y-lohse** [comment]
It looks like some error slipped into the latest version, sorry about that. This one works in dev though, so it will be fixed with the next release which should be very soon.
