### ISSUE TITLE
Help with Saving/Loading (using React/Redux)

### ISSUE THREAD

**Issue by ladyisak** [y-lohse/inkjs#394]
Sooo, I'm using [this tutorial ](https://medium.com/journocoders/create-a-news-game-with-ink-react-and-redux-part-ii-playing-your-game-on-the-web-5216e33043df) as a guide 
(I'm using Next.js rather than Create React App, but that doesn't make that much of a difference, I think) and I'm not quite grasping how to implement saving and loading. 

I couldn't figure out what to google for to look for examples of this kind of thing--I learn best by messing with existing code, and I've got a mild cognitive deficit from inappropriate psych treatment in my early 20s that means just looking at API isn't always helpful for me.  

The other complication here is that the whole thing's in an Electron wrapper so I can upload the final app to itch.io, and I'm not entirely sure where Electron would save data that I'd normally shove into the browser's localStorage.

Any pointers, even if you've just got links to relevant tutorials or repos, are welcome. Thank you!

**Comment by y-lohse** [comment]
Hello,

> I'm not entirely sure where Electron would save data that I'd normally shove into the browser's localStorage.

You can still use localStorage. Each electron app has it's own place on the hard drive for it's own local storage data.

> I'm not quite grasping how to implement saving and loading.

It essentially works like this: when you want to save (ie. when the player clicks a save button or whatever) call `localStorage.setItem('INK_SAVE_1', myStory.state.ToJson());`. When you want to load the game, call `myStory.state.LoadJson(localStorage.getItem('INK_SAVE_1'));`. If that doesn't help, can you tell us more precisely what is not clear or not working for you?

**Comment by y-lohse** [comment]
Closing this, feel free to reopen if you need :)
