### ISSUE TITLE
external funcions not working

### ISSUE THREAD

**Issue by codeartisticninja** [y-lohse/inkjs#40]
This is my ink:

    -> start
    === function get_time() ===
        ~ return "(no external function found)"
    
    === start ===
    It is {get_time()}.
    
    -> END

I export it to web and add an external function in `main.js` :

    var story = new inkjs.Story(storyContent);
    story.BindExternalFunction("get_time",     function(){ return "twelve o'clock"; });

but no matter where I run it, the external function doesn't work

    It is (no external function found).

There are no errors in the console.

**Comment by y-lohse** [comment]
Would you mind sharing the compiled json file here? External functions definitely work, but I've never tried one that came from a fallback. Not that it should make a difference though, but we'll see.

**Comment by codeartisticninja** [comment]
var storyContent = ﻿{"inkVersion":15,"root":[{"->":"start"},"done",{"get_time":["ev","str","^(no external function found)","/str","/ev","~ret",{"#f":3}],"start":["^It is ","G>","ev",{"f()":"get_time"},"out","/ev","G<","^.","\n","end",{"#f":3}],"#f":3}]};

**Comment by codeartisticninja** [comment]
Ah! I completely overlooked the `EXTERNAL` keyword in the documentation.. :p
It works when you put that in.. :)

**Comment by y-lohse** [comment]
Oh good then! :)
