### ISSUE TITLE
Incorrect float operations

### ISSUE THREAD

**Issue by ahayworth** [y-lohse/inkjs#409]
I've run into a strange bug, and the more I look at it, the less sure I am of what exactly is going wrong. Consider the following ink script:
```
# title: bug

~ SEED_RANDOM(1234)
~ temp r = RANDOM(1, 99)
~ temp v = FLOAT(r) / FLOAT(100)
"r" is: { r }
"v" is: { v }
{ v > 0 && v < 1: "v" is within expected bounds. }
```

This is simple:
1. We fix the random number generator for consistent results between runs on any given ~platform~ ink runtime.
2. We generate a random number and divide by `FLOAT(100)`, to ensure we get a fractional result, at least on C# (I don't think #39 applies here - as we'll see in a minute).
3. We print the results and an optional notice if we got an expected result. By definition, we always should get this notice: the lowest value possible is `0.01`, and the highest is `0.99`.

Running via `inklecate -p` yields the expected results:
```
❮ inklecate -cp bug.ink
 ﻿﻿ "r" is: 44
# tags: title: bug
"v" is: 0.44
"v" is within expected bounds.
```

However, running via inkjs, we get something quite unexpected:
```
> .ink start bug


[bot]
"r" is: 32
"v" is: 0

>


[bot]
📕 Ended current story 📕
```

Frankly, I'm a little mystified. I'm aware of some of the parsing difficulties with floats that are actually whole numbers (as talked about in #39). But my testing in a node repl indicates that we should never get 0 as a result, no matter what:
```javascript
❯ node
Welcome to Node.js v12.8.0.
Type ".help" for more information.
> 32 / 100
0.32
> 32 / 100.0
0.32
> parseInt(32) / parseInt(100)
0.32
> parseInt(32) / parseInt(100.0)
0.32
>
```

What seems to be happening is that we're coercing the _result_ of the operations to an integer at some point:
```javascript
❯ node
Welcome to Node.js v12.8.0.
Type ".help" for more information.
> parseInt(0.32)
0
>
```

I've tried to follow the engine code, looking for where this might happen. The only place I can find where we call `parseInt` is when casting a `StringValue` to an `IntValue`. But I can't see where or why we'd need to cast _from_ a string _to_ an int with this simplistic ink script. Why would we? The operations are all numeric, up until the point where we print them out - and even then, we should be going from some subclass of `Value<number>` to `StringValue`, not the other way around.

Any ideas? Do we unilaterally coerce numeric results to `IntValue` rather than detecting the type of the result? That's the only realistic thing I can think of, but I can't quite follow the Value code well enough to see if that's the case.

**Comment by y-lohse** [comment]
> Do we unilaterally coerce numeric results to IntValue rather than detecting the type of the result? 

Not as far as I remember no.

> Any ideas? 

Not right off the bat, but I would agree that this seems different than #39.

If you know how to set breakpoints in a browser, it would be interesting to see what happens when the line `~ temp v = FLOAT(r) / FLOAT(100)` is evaluated. Specifically, how is the `v` variable stored? It should be a <Float>Value with the correct number in it's `value` property. If that's the case then it narrows it down to a printing problem, otherwise there's something wrong with the division itself.

_______

Unrelated, but 

> We fix the random number generator for consistent results between runs on any given platform.

is not quite true. Different ink runtimes use different random implementations, so while they can be seeded, the results will only be consistent as long as the same runtime is used everywhere.

**Comment by ahayworth** [comment]
> Different ink runtimes use different random implementations,

Indeed! I misspoke, and should have said "on any given ink runtime." 😄 

I was able to debug fairly effectively with the vscode debugger - turns out we're actually calling the `/` function with two IntValues, despite having casted them with `FLOAT()`. I don't think inkjs can actually cast between float/int, at all. 😬 

I think the root of the problem is that inkjs defines `FLOAT` to be strictly an identity call here: 
https://github.com/y-lohse/inkjs/blob/master/src/NativeFunctionCall.ts#L330
But upstream ink actually casts it to a float:
https://github.com/inkle/ink/blob/master/ink-engine-runtime/NativeFunctionCall.cs#L349

I can see how this would be really tricky given that javascript doesn't have separate number types. Maybe we could special-case these operations, so that we wrap the result of the identity function directly in a `FloatValue`? That differs from the upstream implementation but maybe it's worth it (because I don't see how casting would work at all, otherwise).

**Comment by y-lohse** [comment]
Thanks for digging in! I'm not sure i understand what's going on yet. 

- Calling `FLOAT(100)` return `100`, which is then converted into an `IntValue` [here](https://github.com/y-lohse/inkjs/blob/master/src/NativeFunctionCall.ts#L155). This is wrong and may be the problem
- But we then try to divide two `IntValue` and should en up [here](https://github.com/y-lohse/inkjs/blob/master/src/NativeFunctionCall.ts#L145), with the result of `IntValue(50) / IntValue(100)`. So `.5` is then passed to [`Value.Create`](https://github.com/y-lohse/inkjs/blob/master/src/Value.ts#L16)… and that should return a `FloatValue`, even if the two operation members were incorrectly detected as `IntValue` before

But clearly that doesn't happen, somehow the result of the division it cast to an int… what am I missing?

**Comment by ahayworth** [comment]
We specifically say `int / int == int` here: https://github.com/y-lohse/inkjs/blob/master/src/NativeFunctionCall.ts#L308

And while javascript is smart enough to return us a float-like thing when we call `50 / 100` in a repl, Ink defines it differently: https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#advanced-numerical-types-are-implicit
So in the case of `int / int`, I think we do the right thing - at least as far as the upstream ink docs are concerned.

**Comment by y-lohse** [comment]
Right, it's the `Math.round` call that I was missing. Damn, that's a tough one.

What do you think about doing some extra checking [here](https://github.com/y-lohse/inkjs/blob/master/src/NativeFunctionCall.ts#L155)? Instead of relying on `Value.create` to infer the type from the variable, we could force the type in some cases. Typically when detecting the operation was `FLOAT`, or when the initial value is a float and we want to keep it that way. We'd have to be caareful not to break any other unary operation but I don't see a better option…

**Comment by ahayworth** [comment]
Yes, that's what my first thought was. Short of somehow introducing a stricter type system into javascript (are there alternate number libraries that we could use instead of the native ones), I'm not sure how else to go about it. :(
