### ISSUE TITLE
Style markup inside paragraph (web only?)

### ISSUE THREAD

**Issue by Selsynn** [y-lohse/inkjs#421]
Hello, 
I love the web / js portage of ink, but I needed in one of my last project to put emphasis on some special words. 
I didn't had it working without tinkering (and didn't had time to tinker in fact)

My idea was to use the md formatting 
`Hello I want to put _emphasis_ on this __word__ like ___this___` get the result 
Hello I want to put _emphasis_ on this __word__ like ___this___

I think it is too confusing to implement the star formatting, but the underscore should be good.

Any idea to not do it? Or how would you tackle the change?
(it seems safer than to accept span html markup)

**Comment by y-lohse** [comment]
Hi ! This is definitely the "correct" way to add markup to ink. In broad lines, something like this:

```
let nextLineInMarkdown = story.Continue();
let nextLineInHTML = convertMarkdwonToHTML(nextLineInMarkdown);
textContainerElement.append(nextLineInHTML);
```

There are a few libraries out there that can take care of the markdown -> html conversion, like [markdown-it](https://github.com/markdown-it/markdown-it#usage-examples) for example.

Hope this helps!

**Comment by Selsynn** [comment]
Ok, that what I thought, thanks for the confirmation. 
Supposing I do it this weekend, would you be interested in a PR to implement it?

Thx for the library as it seems exactly what I want.

**Comment by y-lohse** [comment]
To be honest, I wouldn't really be interested in a PR for that because we want to keep inkjs as close as possible to the original version, so we won't add any extra features :).
