### ISSUE TITLE
Use typescript object type instead of JObject where possible

### ISSUE THREAD

**Issue by tcyrus** [y-lohse/inkjs#448]

**Comment by y-lohse** [comment]
I guess this is related to #449 but can be closed?

**Comment by ephread** [comment]
Actually, I don't quite remember why I wrote `JObject` (pretty sure it was me), but @tcyrus makes an excellent point we should absolutely replace it by `object` and `Record<String, any>` where and when it makes sense. I'll have a look in the future.
