### ISSUE TITLE
No v1.10.3 in npm?

### ISSUE THREAD

**Issue by Tumetsu** [y-lohse/inkjs#452]
I installed this library from npm and wondered why Types didn't work as I expected considering you have `ink.d.ts` in your repository. After a while I noticed that the newest release in npm is `1.10.2` while here it is `1.10.3`. 

Is there some reason to not release the `1.10.3` in npm? I guess I could try to install the package directly from Github or use `1.0.2` and import from `inkjs/engine/runtime`

**Comment by y-lohse** [comment]
No that's not intended, it looks like the automatic [publication to npm is broken](https://travis-ci.org/y-lohse/inkjs/builds/651604156#L377). i'll have to dig a bit to se what's going on :/

**Comment by y-lohse** [comment]
The newest version is now published on npm ([turns out Travis Ci had opted us into a beta that broke the deployments, yay 🤬](https://travis-ci.community/t/npm-deploy-failed-missing-api-key-but-i-have-set-it/6624/12))
