### ISSUE TITLE
Async/await inside external functions

### ISSUE THREAD

**Issue by RokasVaitkevicius** [y-lohse/inkjs#453]
Hello, 

I need to call database in my external function, but I am having trouble doing that. I have this code:
```
story.BindExternalFunction('get_players', async () => {
    const players = await dB.getPlayers()
    return players
})
```
But when inkjs comes to calling this external function in prints this:
`Error: Could not create ink value from returned object of type object null`

I am sure that my db function is working correctly. If I call it from the code, using async/await, it returns an expected result.

Does someone have a suggestion how to call async things from external functions?

**Comment by y-lohse** [comment]
Hello, i'm afraid this won't work at all, for multiple reasons. But mainly, when you use `async` in a function declaration, that function will return a `Promise` that needs to be `awaited` on the other end… the other end being the inkjs code. And that part of the code really can't be `async`.

My suggestion would be to move the player loading code somewhere else, perhaps before the call to `story.Continue()`, so that the external function can returned the preloaded data.

**Comment by RokasVaitkevicius** [comment]
That's unfortunate and I don't think, calling it before continue will work, because I don't really know in the code exact ink context, so that is why I thought of using external functions, which would give me more control and knowledge about what is going on in ink and when should I query DB.
Do you think it would be possible somehow to work around this issue by modifying inkjs code so that it would await those functions and if so could give me some pointers what should I try to change?

**Comment by y-lohse** [comment]
> Do you think it would be possible somehow to work around this issue by modifying inkjs code […]

No 😅Sorry. If you want, the functions are called [here](https://github.com/y-lohse/inkjs/blob/master/src/Story.ts#L1360) but supporting async/await here would be a massive change, as the whole function chain would need to support that and it's a long ass chain.

Also note [this disclaimer](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#important-notes-on-the-usage-of-external-functions) about external functions; querying a database in the middle of ink execution is probably not the best time.

Without knowing the specifics of what you're trying to achieve it's hard to say when the ideal time for the DB query would be, but I don't see a way to do that in an external function call i'm afraid.

**Comment by RokasVaitkevicius** [comment]
Understood. I guess I'll try to preload data that I need somewhere else then. Thanks for you help.
