### ISSUE TITLE
Making state as small as possible

### ISSUE THREAD

**Issue by RokasVaitkevicius** [y-lohse/inkjs#455]
Hello, 

I have a very constrained environment size wise and the main thing that stops me from fitting in those constraints is inkjs state size. I was wondering what can be removed from state, to make it smaller, without loosing player progress?

To capture state I am using `state.ToJson()`. I removed `turnIndices` (I am not sure where they are used?) and `visitCounts` (I don't care about this) from it which helped to reduce state size quite a bit. Is there a way to disable them overall? Because at the moment I am just removing them from the state.

Is there anything else, that can be removed without loosing progress? Maybe something from callstack is not necessary? Maybe `currentChoices` can be removed?

**Comment by y-lohse** [comment]
> I have a very constrained environment size wise and the main thing that stops me from fitting in those constraints is inkjs state size.

Is the problem the size of inkjs in memory, or the size of the exported state?

> Is there a way to disable them overall? 

No I'm afraid there's no built-in way to do that.

> Is there anything else, that can be removed without loosing progress?

So technically there isn't much in the state that should be removed, expect maybe [this](https://github.com/y-lohse/inkjs/blob/56489b3145ae198a21b88bc9cf65560dd2bf9f71/src/StoryState.ts#L341). The `inkSaveVersion` could be removed as well and re-injected later.

All the rest is useful, but not all the time. It depends on what ink features the script uses. `visitCounts` isn't used if the story never cares if some content has been seen before, `storySeed` and `previousRandom` are useless if there is no randomness, etc.
I believe `callstackThreads` and some of the bigger state bits are only useful if you're in a thread for example. So if you make sure to export the state only outside of threads they might be removable. There might be other parts of the state that could be removed if it's exported at the right time, eg. not at a choice point.

**Comment by RokasVaitkevicius** [comment]
The problem is with exported state size I need to minimise it as much as possible. 

Where are `turnIndices` used? 

I tried removing `choiceThreads` and `callstackThreads`, but then on the next choice, story just crashes with error: Cannot read property 'length' of undefined, so I guess they are important.

I am not expert how inkjs works under the hood, but I guess when user  makes a choice,  choice has `originalThreadIndex` and on the next choice, by that `originalThreadIndex` it picks choice from `choiceThreads`. Or how is `choiceThreads` object is used?

I guess [here](https://github.com/inkle/ink/blob/master/Documentation/ArchitectureAndDevOverview.md#callstack-and-threads) it should be explaining how callstack and threads work, but unfortunately this bit of docs is missing.

**Comment by RokasVaitkevicius** [comment]
It seems that it is not really possible to make it smaller without loosing progress and functionality. I decided to just cache it in Redis. As always thank you @y-lohse for your quick responses.

**Comment by y-lohse** [comment]
Sorry, couldn't recall of the top of my head where the different bits of the state are used. As I said there might be other parts that can be stripped from the state *but only in very specific, script dependent situations*. So yeah, tricky, but glad you found a way around :)
