### ISSUE TITLE
Diverting to knots starting with a number

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#46]
The following ink script doesn't work as expected:

```
start
-> 1targetknot
-> END

==1targetknot==
in knot
->DONE
```

As in, it produces no content and just hangs there.

Here's a milder version of the bug:

```
-> top_knot

==top_knot==
start

* option 1 -> 1targetknot

-> DONE

==1targetknot==
in knot
->DONE
```

**Comment by y-lohse** [comment]
The problem comes from the usual finicky number parsing in JS : https://github.com/y-lohse/inkjs/blob/master/engine/Path.js#L111

The dIvert target `1something` is interpreted as an integer instead of a string.

**Comment by y-lohse** [comment]
@joethephish : While researching this, I came across edge-cases where inklecate chokes on some knot names, for example:

```
The answer to life the universe and everything?
-> 42

== 42 ==
Nope.
->DONE
```

> ERROR: 'test.ink' line 2: Expected end of line but saw ' 42'
> ERROR: 'test.ink' line 4: Expected end of line after knot name definition but saw '42 =='

I get why names like `42` or `1.3` can't work, but the doc only says 

> the name needs to be a single word with no spaces

This is mostly FYI though, I'd say a compiler error is fine in this case and there's no need to muddy up the docs.

**Comment by joethephish** [comment]
Yes, the approach to identifiers should be pretty much "anything but a number or punctuation". Right now there is a bit of a debate as to whether that should be `[A-Za-z0-9_]`(current implementation) or it should allow certain sets of non-English character ranges. Anyway, the behaviour above is pretty much as expected, except that the error reporting is clearly not ideal.
