### ISSUE TITLE
Exception not thrown, when invalid operation is done

### ISSUE THREAD

**Issue by RokasVaitkevicius** [y-lohse/inkjs#464]
In some cases inkjs is not throwing exceptions when it should and just silently kills the story. This makes debugging the story quite difficult.

I have one example, where I do '||' operation on string variables. Inky editor shows, that it cannot perform this operation, but when I do the same operation using inkjs it just silently stops.

You can reproduce this issue by copying this script to inky editor:

```
-> open

VAR var1 = ""
VAR var2 = ""

====== open =====
+ Launch
Launching

{ var1 || var2:
 some text
}
-> DONE
```

If you press 'Launch' it will crash with error: `Line 10: Cannot perform operation '||' on String`. Then export it 'for web' and open it using the index file and press 'Launch'. There is nothing in the console, no error, nothing.

As I was trying to figure out why is that I found that error should be thrown here:
https://github.com/y-lohse/inkjs/blob/47638989e0d963d630c5b89fb24ddc35f9d01780/src/NativeFunctionCall.ts#L132
But for some reason it doesn't bubble up.

Without these exceptions it gets really hard to debug the story, because sometimes you are deep in it and it just stops and because of that I have to try to recreate that path in inky editor which is very time consuming.

Does anyone have any ideas why that could be happening?

**Comment by y-lohse** [comment]
After some investigation, this is the expected behavior and is in line with the C# runtime. You are correct that the errors are not thrown, but they are collected in the story state. You can check `story.state.currentErrors` after the call to `Continue` to read them. I assume this is what inky does as well.

**Comment by joethephish** [comment]
I think I should really change this in C# version, so you get exceptions unless you attach an error handler, rather than requiring you to check currentErrors. We’ve been caught out by that ourselves!

**Comment by RokasVaitkevicius** [comment]
Thank you for replies. Now I'll know, that errors can be found in that `currentErrors` array. I'll need to make sure to check that in the code then. 

Still, it is quite annoying, because to me it seems to be more intuitive to just throw an error, because at least in this case, which I posted, story still crashes and cannot continue, so either way it is dead, but thrown error would at least make debugging easier.

I don't know, what should I do with this issue? Should I leave it as a feature request or should I just close it?

**Comment by joethephish** [comment]
Feel free to close. It’s a valid feature request but it really belongs in inkle/ink
