### ISSUE TITLE
VariablesState.SetGlobal typedef is overly narrow

### ISSUE THREAD

**Issue by furkle** [y-lohse/inkjs#469]
Currently, there's a subtle but significant difference in how the `VariablesState.SetGlobal` function works in practice, and how the type definition indicates it should be used. The function itself accepts both `InkObject`s and values which may be legally casted into `InkObject`s. However, the type definition for the method signature only accepts `InkObject` as the variable value, forcing the consumer to call `Value.Create` themselves even though the function implementation will do that for them.

**Comment by ephread** [comment]
Very good point @furkle, it seems I mistakenly turned a C# `object` into a `InkObject` instead of `any`.

@y-lohse I believe this is the line in question: https://github.com/y-lohse/inkjs/blob/master/src/VariablesState.ts#L59

Should be easy to fix!

**Comment by furkle** [comment]
@ephread Yeah, I actually only noticed because I asked in the Inkle chatroom "how am I supposed to coerce values into `InkObject`s to set globals?" and Joe said "you don't have to." That's when I saw that `SetGlobal` already calls `Value.Create`, and realized it was probably a very minor bug. Very easy to get mixed up between `object`, `JObject`, and `InkObject` 🙂

**Comment by ephread** [comment]
The fix is merged in `master`. Thanks again for catching this @furkle!
