### ISSUE TITLE
Multiple renovate PRs pending due to missing spread operator support in node.js 7.10.1

### ISSUE THREAD

**Issue by ephread** [y-lohse/inkjs#473]
Three PRs (#407, #435, #443) can't be merged automatically because node.js 7.10.1 doesn't support spreads in literals. [MDN suggests](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility) that this feature is supported from 8.3.0 onwards.

@y-lohse do you think it's safe to bump the version used in the CI and drop support for versions below?

**Comment by y-lohse** [comment]
I didn't realize we were still running node 7 😱. We should definitely upgrade to whatever is in LTS now, I think it's version 12. I'll take a look, thanks!

**Comment by ephread** [comment]
Awesome, thanks for taking care of this!

I'm going to migrate to jest 25 manually and close #443.

**Comment by ephread** [comment]
All done!
