### ISSUE TITLE
user session and async play?

### ISSUE THREAD

**Issue by spikelab** [y-lohse/inkjs#49]
Hi there,

finding out about inkjs just made my day so a huge thank you to everybody working on this.

I'm trying to build an online game with ink and I need some way for players to register and save/resume their games. Is that something that is possible or even make sense to be in inkjs? Do you have any recommendation on how to handle this?

If it makes any sense, ideally I'd have inkjs just be the story engine/API (that's what I was trying to build). Reading about ink it seems that's how it's designed to begin with so that it can be plugged into Unity etc. What I'm envisioning is basically a state machine that can receive commands from whatever input (web user clicking, email, facebook bot) and advancing to whatever section based on the story + action. Does that make any sense? am I just way off track?

thank you in advance and happy 2017,

Spike

**Comment by y-lohse** [comment]
Hi!

> thank you to everybody working on this.

Appreciated :-)

> Does that make any sense? am I just way off track?

Nope, you're not off track at all. Ink is indeed designed to be just the story engine for a game, with every other part of the game being handled by whatever other technology -- Unity, a web server, etc.

> I'm trying to build an online game with ink and I need some way for players to register and save/resume their games. Is that something that is possible or even make sense to be in inkjs? Do you have any recommendation on how to handle this?

Ink won't be of much help to register your users, but the story state can indeed [be saved and resumed](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#saving-and-loading) at will. 

So you'd presumably have a database with your players, and for each one of them the latest saved story state. And when a player makes a choice, you'd boot the story back up from that save, continue for a while, then save the new state when the player is done.

Hope that helps!

**Comment by spikelab** [comment]
Hello @y-lohse ,

thank you for your input, it totally makes sense. I'll have to figure out how responsive that's going to be tho; since it's http/stateless I would have to do a resume/save for each single step of the story, which sounds expensive since as far as I understand each time I'd have to rewrite the entire json. Am I missing something?

**Comment by erkyrath** [comment]
No, that's the way it pretty much has to work. It's not an unreasonable amount of work for a server to do, though. 

If you find that the real-life server load is too high, here's a possible idea: modify the engine to support incremental updates. That is, generate just the differences to the JSON state as opposed to handing you the entire current state at the end of the turn. I don't think either the JS or C# engines supports this, but it would probably be a simple modification.

(I'm thinking about the idea of storing the state key-by-key in a database -- mongodb or something -- instead of dropping in the whole JSON as a text file.)

**Comment by spikelab** [comment]
thanks @erkyrath . I thought about mongodb, but then it's really only going to make a difference if keys can be handled separately like you said. I think for experimenting I'll just start with saving/resuming the whole thing as discussed and then see how that works out in terms of latency. Also I don't know how big of a json file I'm going to end up with for the story I wrote, I guess that's another big variable (I saw the json for the intercept story is ~150Kb).

**Comment by erkyrath** [comment]
Oh -- the *game file* JSON for Intercept is 150kb, but the *game state* JSON is only about 3kb. (This is what you get from story.state.jsonToken.)

**Comment by spikelab** [comment]
ah-ha!, glad I asked, that's a lot more manageable and probably good enough. It also solves the problem I was pondering if the same user wanted to start multiple games, then I just have to save multiple state files.

Thanks to both of you for the support. I was gonna close the issue, but then one last thing, even tho only tangential to this, hope that's ok: do you know of any web engine that I could plug ink into? I'm looking at something very simple, so not godot, but slightly more complex than the template with the interceptor. For start I'd just like to display full screen images with a section underneath for the text, similar to the old school strategy games like monkey island or indiana jones if you're familiar with those.

thanks!

**Comment by y-lohse** [comment]
Sorry, I can't help you at all with that last one :-). Since no one else has replied here, I'll close the issue but I hope you found your answer elsewhere!
