### ISSUE TITLE
Updates to 0.7.0

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#50]
https://github.com/inkle/ink/compare/0.6.4...0.7.0 :hammer_and_pick:

**Comment by y-lohse** [comment]
Quick status update: I've now translated nearly all the code, just some serialisation left to do. Then I'll have to read it carefully again and it'll be time for testing the crap out of it.

**Comment by joethephish** [comment]
Fantastic! Looking forward to taking it for a spin :)

**Comment by y-lohse** [comment]
Something I have to get back to later:

```
LIST GuardsOnDuty = (Smith), (Jones), Carter, Braithwaite

On duty {GuardsOnDuty}
~ GuardsOnDuty = LIST_INVERT(GuardsOnDuty)
On duty {GuardsOnDuty}
```

Gives 

On duty Smith, Jones
On duty Smith, Jones (this one is wrong)

But remove the first list print and the inversion works. Might be a bug unrelated to lists?

**Comment by y-lohse** [comment]
Right, aside from that, things seem to be working fine! I still need to test all the list functions individually, but the various examples provided in the documentation are all good -- including the crime scene.

**Comment by joethephish** [comment]
Awesome!

**Comment by krageon** [comment]
I'm using this in a development environment, as a prototype for a system that will be used in production eventually. So far I'm not running into any issues with this branch - if I do encounter anything strange I'll poke you about it.

**Comment by y-lohse** [comment]
Thanks for the feedback, that's great to know. I haven't had time to work on this lately, but I assume I'll be finished soon.

**Comment by y-lohse** [comment]
I found the origin of the bug mentioned above and it is not related to lists. It's sort of serious though, and I'd like some feedback on the fix from @joethephish if you don't mind.

Similar to some other cases that @joningold fixed, the [`VariableState.globalVariables`](https://github.com/y-lohse/inkjs/blob/master/engine/VariablesState.js#L88) is currently assigned by reference and not by copy. This means that if you take a state snapshot, change a variable, and restore the snapshot, the variable will *still* be changed. Ouch.

```
VAR gold = 5

"Here, beggar, have this coin."
~ gold -= 1
You now have {gold} gold
```
The gold-decrementing-line is called more than once because we're checking for glue, and you end up with this output:
```
"Here, beggar, have this coin."
You now have 3 gold
THE END
```

Deep copy in JS is a bit weird, so I was looking for an alternative. If I'm not mistaken, all variables in `VariableState.globalVariables` are `Values`, so I should be able to clone them [like this](https://github.com/y-lohse/inkjs/blob/lists/engine/VariablesState.js#L91). Do you see potential side effects to this approach, or a better way to handle this?

**Comment by joethephish** [comment]
Ouch indeed! Well glad you managed to find it :-)

You know, I *think* you don't need to clone the individual values, but just the dictionary itself, since the values are treated as immutable - even all list operations end up creating new values when a list's contents are changed.

So, I *think* it should be enough to do this:

    this._globalVariables = {};
    for (var name in toCopy._globalVariables){
        this._globalVariables[name] = toCopy._globalVariables[name];
    }

(Or is there even a shortcut to do that in JS?)

**Comment by y-lohse** [comment]
Yep, there's [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) and it seems to work. Thanks!

A couple more tests and lists will be good to go :white_check_mark:

**Comment by dexterlohnes** [comment]
Thanks so much for your work on this @y-lohse! I'm amazed at how easy it was to get a simple server-side IF thing working last night thanks to the hard work of you and the guys at Inkle.

**Comment by y-lohse** [comment]
Ok, I'm done testing lists! New version coming out. There might still be some ironing out to do, but I couldn't find anything.

**Comment by krageon** [comment]
That's really cool news :) Keep up the good work!

**Comment by joethephish** [comment]
Congrats!! Good timing too - we just got back from GDC, so I should have a moment to roll it into a new version of Inky :)
