### ISSUE TITLE
InkJs gifts me 10 coins  💸

### ISSUE THREAD

**Issue by chromy** [y-lohse/inkjs#514]
## Describe the bug
I was trying [this example](https://github.com/inkle/ink-library/blob/master/Snippets/print_num.ink) in InkJs and instead of "You have fifty-eight coins." it prints "You have sixty-eight coins."

I think the issue is [this line](https://github.com/y-lohse/inkjs/blob/master/src/NativeFunctionCall.ts#L308) which should be `Math.floor` rather than `Math.round` that seems to fix the problem.

## To Reproduce
I made a glitch showing the behaviour: https://lateral-immediate-channel.glitch.me/, Code: https://glitch.com/edit/#!/lateral-immediate-channel?path=index.html 

## Expected behavior
Should output "You have fifty-eight coins."

## Ink files

[story.json.txt](https://github.com/y-lohse/inkjs/files/4674124/story.json.txt)
[story.ink.txt](https://github.com/y-lohse/inkjs/files/4674125/story.ink.txt)

## Environment
 - OS:  macOS & Linux (w)
 - Web browser version: Chrome 81.0.4044.138
 - Node version: also v12.3.1
 - _inklecate_ version: 0.9.0
 - _inkjs_ version: 1.10.4 & 1.9.0

## Additional context
See https://chromy.github.io/ink-proof/#!/result/17

**Comment by ephread** [comment]
Awesome @chromy, thanks for the detailed report and the PR. You've fixed that [this disabled test](https://github.com/y-lohse/inkjs/blob/master/tests/specs/ink/Logic.spec.js#L33) as well!
