### ISSUE TITLE
Run the test suites against both ink(-es2015).js and the TypeScript sources

### ISSUE THREAD

**Issue by ephread** [y-lohse/inkjs#523]
After v0.9 is merged I'd like to make a few changes to our test architecture (again).

I want to run the tests both with TypeScript and JavaScript! Three reasons:

1. I can't reasonably debug the JavaScript tests, since they rely on the transpiled/rolluped code; I have to use stuff like `console.log`, it slow, clunky and it takes forever to rebuild;
2. the coverage metrics of the tests written in TypeScript are not included the final report;
3. if we run the tests in TypeScript directly, we should be able to get rid of the deprecated `remap-istanbul` I put in a while ago and include all the tests in the coverage.

To summarise: TypeScript for debug & coverage, JavaScript to make sure the babelised-rolluped code is still passing the tests.

I plan to move the tests in TS (it's very quick), but also compile them to JS. By using the environment variables, I'll be able to choose which `Story` to load in `common.ts`. When jest is ran against the JavaScript files, it'll load `ink.js` and `ink-es2015.js`. When it's ran against TypeScript file, it'll load the TypeScript class directly.

Something like:

```json
{
    "test": "npm run-script test:javascript && npm run-script test:typescript",
    "test:javascript": "INK_TEST=dist jest --config=jest.javascript.config.js && INK_TEST=legacy jest --config=jest.javascript.config.js",
    "test:typescript": "jest --coverage",
}
```

I'll need to work out the type definition (probably just a `declare module "*";` somewhere) for the compiled files, but it should be doable!

What do you think?

**Comment by y-lohse** [comment]
I understand the motivation and mostly how we'd do it.

> I plan to move the tests in TS (it's very quick), 

Changing the extension and slapping a few `:any`, or did you have more in mind?

> but also compile them to JS. 

When would we do this? Still on the CI as part of the testing step?

_______

My other slight concern is execution time, the Ci task takes more than a minute now. We should be able to use travis build stages and run all 3 test suites at the same time to speed things up. Probably best to do this in a separate PR though.

**Comment by ephread** [comment]
> Changing the extension and slapping a few :any, or did you have more in mind?

Nope, that's about it!

> When would we do this? Still on the CI as part of the testing step?

Good question, probably as part of the step test. Compiling the specs should be very fast.

> My other slight concern is execution time, the Ci task takes more than a minute now.

You folks in the JavaScript world are spoiled, my Swift builds/tests easily go pass the 15m mark, and that's on Github Actions! It would probably be even slower with Travis.

So we're already running them three times at the moment, because there's one for ink.js, one for ink-es2015.js and one for coverage. My guess it that the overall time spend building and testing wouldn't change much.

> We should be able to use travis build stages and run all 3 test suites at the same time to speed things up. Probably best to do this in a separate PR though.

Absolutely! I've grown a mild dislike of Travis, so my knowledge of their CI is limited. I'll let you take the lead on this!

**Comment by y-lohse** [comment]
> You folks in the JavaScript world are spoiled, my Swift builds/tests easily go pass the 15m mark

Don't worry we make sure to bloat our projects so build times go past the 10m mark as well 😜

> So we're already running them three times at the moment

Right, I forgot there was a coverage run too. Cool then.

> Absolutely! I've grown a mild dislike of Travis, so my knowledge of their CI is limited. I'll let you take the lead on this!

No problem, I'm quite familiar with travis. That said I don't know how much longer they'll be around and wouldn't mind learning github actions, so we'll see.
