### ISSUE TITLE
Rewind story, like in inky editor?

### ISSUE THREAD

**Issue by bitbutter** [y-lohse/inkjs#63]
At a couple of points in my script I'd love to be able to give players a chance to 'do over' a section from some point before the last choice they made.

The naive fix was to use a divert to get back to the desired point. The trouble is that the previously chosen choices are no longer available of course, while i'd like them to be (as if time had been rewound). And I don't want to make them sticky because in other paths the player takes, the choices should disappear. 

I wondered if there's currently an ability to 'rewind' the state of the story in inkjs as there seems to be in the inky editor. Failing that is there some other approach i should look into? (some kind of save and restore routine?).

Thanks for this great library!

**Comment by y-lohse** [comment]
> some kind of save and restore routine?

Precisely! There is no rewind per say, but saving and restoring should do the trick :-)

**Comment by joethephish** [comment]
(See `var saved = yourStory.state.toJson()` and `yourStory.state.LoadJson(saved)` :-) )
