### ISSUE TITLE
ink 0.7.3 update

### ISSUE THREAD

**Issue by joethephish** [y-lohse/inkjs#66]
ink 0.7.3 has quite a few improvements, but just one small one that requires an update from inkjs for the runtime. See this changelist:

https://github.com/inkle/ink/commit/798f51216fa06023082bf01ecac5d0e4c465e316

**Comment by y-lohse** [comment]
Thanks! ETA this week-end or the next one.

**Comment by y-lohse** [comment]
Full diff : https://github.com/inkle/ink/compare/0.7.1...0.7.3

**Comment by y-lohse** [comment]
Changes up to 7.3 have been ported, still left are changes to 7.4 : https://github.com/inkle/ink/compare/0.7.3...0.7.4

**Comment by y-lohse** [comment]
I just published [version 1.6.0](https://github.com/y-lohse/inkjs/releases/tag/1.6.0) :tada:

**Comment by joethephish** [comment]
Woohoo! Thanks :)
