### ISSUE TITLE
Typings for intellisense support

### ISSUE THREAD

**Issue by Leopotam** [y-lohse/inkjs#74]
This module should provides typings for proper usage with flow / typescript type checking and intellisense support.

**Comment by y-lohse** [comment]
Yes, that would be good! However it's definitely not something I'll have time to work on in the foreseeable future, so if you (or anyone else) wants to open a PR for this, you're more than welcome.

**Comment by Leopotam** [comment]
@y-lohse no need anymore - i wrote fat-free ink analogue in typescript and c#. You can close this issue if you want, thanks for your time.

**Comment by y-lohse** [comment]
Cool, î'll do that then, we'll see if and when someone else needs this.
