### ISSUE TITLE
Trouble with Inky, ink, inkjs version numbers

### ISSUE THREAD

**Issue by OffworldHometown** [y-lohse/inkjs#75]
I'm trying to run one of my ink stories with the serverless browser template, but I get an error saying, "Uncaught Version of ink used to build story was newer than the current verison of the engine ink.js.5044" I'm using Inky 0.8.0, ink 0.7.4, and inkjs 1.6.0. The inkjs 1.6.0 release says it should work with ink 0.7.4, so I'm not sure what to do.
Thanks for looking at it!
EDIT: If I go into the JSON file from inklecate and change "inkVersion":17 to "inkVersion":16, everything seems to run fine. I'm worried that there's going to be some version compatibility issue that I'm just papering over though.

**Comment by y-lohse** [comment]
Hi, that's probably because the ink.js files in the templates were outdated. I've just updated them in 731919342dd078290daf062c3897c80a7f0530d4, so if you replace your local copy of the file it should work fine ;)

**Comment by OffworldHometown** [comment]
It works- thank you!
