### ISSUE TITLE
Use a js Map for InkLists

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#78]
InkList are implemented in a hacky way at the moment, leading to problems like #76. It's probably better to use js Maps somehow to accomplish the list behavior.

**Comment by NQNStudios** [comment]
I'm gonna try and do this one.

**Comment by ephread** [comment]
@NQNStudios just to give you a heads up, this has already been taken care of while porting the code to TypeScript! 😉

**Comment by y-lohse** [comment]
Yeah sorry, I forgot to update it. Closing this issue now to avoid further confusion.
