### ISSUE TITLE
Glue sometimes gluing too much

### ISSUE THREAD

**Issue by joningold** [y-lohse/inkjs#79]
There's a bug in ink-js somewhere compared to the main c# runtime; sometimes a stack of functions will cause an additional glue on the end, where the c# doesn't.

I don't have a minimal source for this! But I'll try to capture one.

**Comment by y-lohse** [comment]
Turns out what I thought was a bug is normal:

```
= diverted_glue
More <>-> diverted_glue_target

= diverted_glue_target
glue
```

Gives `More  glue` (with 2 spaces), but inky must auto-correct that.

So if you have any more details on that extra glue bug, even a not-so-minimal example, I'd be happy to investigate!

**Comment by y-lohse** [comment]
@joningold can you let me know if the problem persists in v1.7.0 please ?

**Comment by y-lohse** [comment]
Since it's been 2 years and a bunch of versions, i'm declaring this issue "lost in limbo". We can always reopen a new issue of we run into gluing issues again!
