### ISSUE TITLE
NodeJS code of demo

### ISSUE THREAD

**Issue by KnowsCount** [y-lohse/inkjs#796]
In order to understand it more, can you also open source the NodeJS code of your [demo](http://yannick-lohse.fr/inkjs/) provided? I am still kinda noob and therefore does not quite see what is going on in the README file. I am currently working on a ReactJS web app which would require something alike.

**Comment by KnowsCount** [comment]
or, can someone help?

**Comment by y-lohse** [comment]
Hello, you can find the code of the demo [here](https://github.com/y-lohse/inkjs/blob/gh-pages/index.html#L147) (on the gh-pages branch of this repo). You may also find this template useful : https://github.com/y-lohse/inkjs/tree/master/templates/browser_serverless

Good luck!

**Comment by KnowsCount** [comment]
Oh – I seriously did not see this.. very dumb of me indeed. Beg for your indulgence
