### ISSUE TITLE
Viewcount and choices

### ISSUE THREAD

**Issue by PaulStanley** [y-lohse/inkjs#8]
Great progress! In my tests, one-shot choices are displaying repeatedly, apparently because it is not being noticed that the target has already been visited.

**Comment by PaulStanley** [comment]
... and today it seems to be working perfectly, so presumably my error. Sorry.

**Comment by y-lohse** [comment]
Wow, somehow I wasn't github-watching my own repo, just saw this one, sorry!

But yes, you're rigth, there was a bug like that. I think I fixed it in b7f9ebb2311dac4e063a6806c5f0558bf50017ea so the latest versions shoudl be fine :-)

**Comment by PaulStanley** [comment]
Thanks. I thought it was just me. The speed you have done this is impressive.



On 10 Jun 2016, at 18:12, Yannick Lohse <notifications@github.com<mailto:notifications@github.com>> wrote:


Wow, somehow I wasn't github-watching my own repo, just saw this one, sorry!

But yes, you're rigth, there was a bug like that. I think I fixed it in b7f9ebb<https://github.com/y-lohse/inkjs/commit/b7f9ebb2311dac4e063a6806c5f0558bf50017ea> so the latest versions shoudl be fine :-)

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/y-lohse/inkjs/issues/8#issuecomment-225241117>, or mute the thread<https://github.com/notifications/unsubscribe/ACGpN_gmkUJA83vMFk1mKBC9tYnSZlp1ks5qKZsNgaJpZM4Iw3qJ>.
---------------------------------------------------------------------------------------
 This email has been scanned for email related threats and delivered safely by Mimecast.
 For more information please visit http://www.mimecast.com
---------------------------------------------------------------------------------------
