### ISSUE TITLE
No `ink.js` provided in releases

### ISSUE THREAD

**Issue by clembu** [y-lohse/inkjs#830]
Hi. I notice your readme mentions grabbing the `ink.js` file from the release page, but all assets available are the source code, which does include a couple `ink.js` files in the `templates/` directory, but the latest commit on those dates from 2 years ago.

Maybe you'd want to update your readme to only mention npm installation, add compilation instructions to get that `ink.js` file, or include the compiled file in the releases.

**Comment by y-lohse** [comment]
Thank you, that section was really out of date!
