### ISSUE TITLE
Ink v1.0.0 support

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#836]
The time has come again! Ink 1.0 is here, and we have some catching up to do.
The diff can be found here: https://github.com/inkle/ink/compare/0.9.0%E2%80%A6v1.0.0

Not sure when we'll start this, or how, but here's the list of files that need change, for tracking:

- CallStack
- Choice
- ChoicePoint
- Container
- ControlCommand
- DebugMetadata
- Divert
- Error
- Flow
- Glue
- INamedContent
- InkList
- JsonSerialisation
- ListDefinition
- ListDefinitionsOrigin
- NativeFunctionCall
- Object
- Path
- Pointer
- Profiler
- Properties/AssemblyInfo
- PushPop
- SearchResult
- SimpleJson
- StatePatch
- Story
- StoryException
- StoryState
- StringJoinExtension
- Tag
- Value
- VariableAssignment
- VariableReference
- VariablesState
- Void

As usual any help is more than welcome, I haven't really touched the codebase in a while so it's going to be an interesting one 😅. If you would like to contribute, announce yourself in this issue with whatever file(s) you'd like to tackle. I'll set up a new branch that we can code against.

**Comment by landryyrdnal** [comment]
May I suggest to add to this list the increase of the Unicode character ranges for foreign languages, as it has been improved for Korean and Latin1 for french accents in the v1.0.0 of Ink ? I would be glad to help you in this, but I definitely don't know where to look, and I’m very new to JS.

**Comment by ephread** [comment]
🎉 Here we go again! I'll start looking into it this weekend probably!

**Comment by y-lohse** [comment]
> May I suggest to add to this list the increase of the Unicode character ranges […]

Anything in the v1 would be part of the changes above :) That being said, I believe the unicode character ranges are a change to the ink compiler, the runtime doesn't need anything particular to support them.

**Comment by ephread** [comment]
@y-lohse There are some changes in the tests, I'll work on porting those first!

**Comment by y-lohse** [comment]
Yup that makes sense. I'll create the main PR and start with some low hanging fruits to get back into the swing of things.

**Comment by ephread** [comment]
FYI I've also created `v1.0-tests` on here (not on my fork), because porting the tests will require multiple PRs.
