### ISSUE TITLE
Fix BuildStringOfHiearchy

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#9]
The BuildStringOfHiearchy is currently broken because there is no StringBuilder class in javascript that can be passed around as a reference. It would probably be cool to create a very small one and use it at least there.

**Comment by joethephish** [comment]
Note that `BuildStringOfHierarchy` is not really a very necessary requirement of the entire thing! It's just a function that I found useful when debugging. Unless of course you find it useful yourself!

**Comment by y-lohse** [comment]
Yeah I just wrote the issue so I don't forget about it in case someone needs it, but it's not really a priority :-)
