### ISSUE TITLE
Uncaught (in promise) Error: Version of ink used to build story was newer than the current version of the engine

### ISSUE THREAD

**Issue by jjnyx** [y-lohse/inkjs#905]
I tried to fetch a .json file following the demo here: https://github.com/y-lohse/inkjs#working-with-a-json-file.
It looks like the [main.js](https://github.com/y-lohse/inkjs/blob/master/templates/browser_with_server/main.js) is no longer working with the newer version inky 0.12.0 and ink version 1.0.
When I tried the html file in the browser, I got this error:

Uncaught (in promise) Error: Version of ink used to build story was newer than the current version of the engine
    at new h (ink.js:1)
    at main.js:12

Can anyone tell me how to fetch a .json file for the newer version?

**Comment by y-lohse** [comment]
Apologies for the lack of replies! It looks like the problem in this case is more that the inkjs was out of date — you can grab a new one from here for example https://unpkg.com/inkjs. Although inky has probably been updated in the meantime.
