### ISSUE TITLE
Story values not reflected post-choice inside a 'onMakeChoice' event callback

### ISSUE THREAD

**Issue by jabza** [y-lohse/inkjs#919]
## Describe the bug
When checking the currentText, currentChoices and canContinue of the Story object within onMakeChoice, these are still the old values.

## To Reproduce
story.onMakeChoice = () => console.log(story.currentChoices, story.canContinue);

## Expected behavior
The Story object read at the point of the event firing should reflect the state of making the choice.

## Additional context
I was able to locally fix this in two ways:

1: Await a 0ms timeout inside the event callback before accessing Story.canContinue.
2: Move the invocation of .onMakeChoice to the end of ChooseChoiceIndex() inside Story.js.

**Comment by y-lohse** [comment]
Hi! So I don't think that's a bug, as far as I know this is by design. We follow whatever is done in https://github.com/inkle/ink — could you confirm the same thing is happening with the C# version?
