### ISSUE TITLE
Setting InkList variables

### ISSUE THREAD

**Issue by AdrienLemaire** [y-lohse/inkjs#920]
## Describe the bug

![](https://i.imgur.com/SJyfVEC.png)

## To Reproduce
```ts
import { InkList, InkListItem } from "inkjs/engine/InkList";
import { ListValue } from "inkjs/engine/Value";

const myList = new InkList()
data.forEach((item) => {
  myList.Add(new InkListItem("myList", item.strName), item.intValue);
});

// Option 1
const value = ListValue.Create(myList);
ink.variablesState.SetGlobal("myList", value)

// Option 2
ink.variablesState.$("myList", myList);
```

## Expected behavior
the ink story is updated with the global LIST variable `myList` and the new content added.

## Environment
 - OS: Linux
 - Web browser version: Chrome 
 - _inkjs_ version: 2.0.0

## Additional context
I'm trying to modify the initial value of a list in an ink story, and am failing to because of the error above. Wondering if this is due to the `Value.Create` internal call, when Value is an abstract class ?

I'm having trouble to handle this InkList to InkObject conversion. What would be the appropriate way to replace an InkList variable with new content ?

As a side note, the type of `VariableState.$` should be updated to allow a single parameter for read access. Right now, I must call `ink.variablesState.$("myList", undefined)` if I want to read the content.

```diff
-    $(variableName: string, value: any): any;
+    $(variableName: string, value?: any): any;
```

**Comment by AdrienLemaire** [comment]
After spending 5 hours debugging the code, I found a convoluted way to update a global list.

```ts
import { InkList, InkListItem } from "inkjs/engine/InkList";
import { ListValue } from "inkjs/engine/Value";

# 1. Create fake InkList
const myList = new InkList()
data.forEach((item) => {
  myList.Add(new InkListItem("myList", item.strName), item.intValue);
});

# 2. Retrieve a copy of the existing ListValue
const listValue = ink.variablesState.GetVariableWithName(
  "myList"
)! as ListValue;

# 3. Mutate the ListValue value with our new list
listValue.value = myList

# 4. Replace the global ListValue
ink.variablesState.SetGlobal("myList", listValue);

# 5. Get ink to use the new list when calling Continue
ink.variablesState.SnapshotDefaultGlobals();
```

**Comment by y-lohse** [comment]
Hi! Thanks for reporting this and a workaround too. I haven't touched inkjs in a while and probably won't for some more time, so I have no idea what could cause this at this point. If you want to provide a PR to fix the issue though I'd be happy to assist :)
