### ISSUE TITLE
state.toJson() currentChoices[x].index always 0

### ISSUE THREAD

**Issue by vincentkerdraon** [y-lohse/inkjs#932]
## Describe the bug
When exporting the state to JSON.
- in v19: `currentChoices[x].index` was the index to use in `story.ChooseChoiceIndex()`.
- in v20: `currentChoices[x].index` is always 0.

## To Reproduce
- Go to a knot with at least 2 choices.
- Export state to JSON. 
- check exported JSON.

## Expected behavior
- currentChoices[0].index=0 for first choice 
- currentChoices[1].index=1 for second choice 

## Environment
 - OS: Linux Mint
 - running in v8 engine.
 - _inklecate_ version: `Ink v1.0` (https://github.com/inkle/ink/releases/tag/v1.0.0)
 - _inkjs_ version: `v2.0.0` (https://unpkg.com/inkjs@2.0.0/dist/ink-es2015.js)

## Additional context
This is not a high priority, I can count the position in the array instead. 
Thank you.

**Comment by smwhr** [comment]
It looks like it's fixed in the upcoming release !

<img width="620" alt="image" src="https://user-images.githubusercontent.com/1090485/197197556-917da116-07ea-4a8f-adc5-728bc42ef1bc.png">
