### ISSUE TITLE
[Compiler] What name should we use for the JavaScript version of inklecate?

### ISSUE THREAD

**Issue by ephread** [y-lohse/inkjs#935]
Per #933, the JavaScript version of inklecate is likely to have a slightly different interface compared to the original implementation. To avoid confusion, I think we should name the command differently.

Before running a poll, I'd like the input of the community. We currently have a short list of names, and new options are welcome! I'll update this issue with any suggestions made either here or on Discord.

**——— EDIT ———**

Here are all the suggestions made by the community:

1. inklenode
2. inklet
3. inklescript
4. nodlecate
5. inkjs-compiler
6. inklecatejs
7. inkycatjswriter (😂 – Not part of the poll!)

I would also like to suggest another name 🙃 (NO SPOILERS!):

![Screen Shot 2022-02-20 at 20 59 47](https://user-images.githubusercontent.com/722366/154862109-8e8e8cd5-e2db-4e82-97af-a47bedc1524c.png)

## Poll

**Vote now!** – _Click on the option you prefer the most._

[![](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/inklenode)](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/inklenode/vote)
[![](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/inklet)](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/inklet/vote)
[![](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/inklescript)](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/inklescript/vote)
[![](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/nodlecate)](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/nodlecate/vote)
[![](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/inkjs-compiler)](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/inkjs-compiler/vote)
[![](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/inklecatejs)](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/inklecatejs/vote)
[![](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/the%20ancient%20name)](https://api.gh-polls.com/poll/01FWCBPNXGYRQRFD4652KW45NW/the%20ancient%20name/vote)

**——— EDIT 2 ———**

The community spoke. It shall be called `inkjs-compiler`! 🎉

**Comment by Shepard** [comment]
> I don't know what I would vote for yet, but extra suggestion :)
> 
>     * inkjs-compiler
> 
>     * inklecatejs

I like names that say what's in the tin so I second both of these.

**Comment by joethephish** [comment]
I agree, speaking from inkle experience with giving new specific names to everything, I’d suggest `inklecatejs` or `inkjs-Compiler` for clarity, and I like `inklecatejs` is my favourite.

**Comment by bendodson** [comment]
I also agree with `inklecatejs` or `inkjs-compiler` (but could be tempted by `inklescript`)

**Comment by justinmulwee** [comment]
I like `inkjs-compiler` because it's the clearest. Some ink users won't know what inklecate is. Let's save the cool branding names for our apps and games :)

**Comment by ephread** [comment]
Thanks for your input everybody, as promised, I've added a poll in the first comment. Feel free to vote!
