### ISSUE TITLE
Ink v1.1 support

### ISSUE THREAD

**Issue by smwhr** [y-lohse/inkjs#978]
The time has come again! Ink 1.1 is here, and we have some catching up to do.
The diff can be found here: https://github.com/inkle/ink/compare/v1.0.0...v1.1

Things that have been touched : 

**Core** 
- The core play loop can now expose tags for choices

**Compiler : Variable tags and tags in choices**
- `compiler/InkParser/InkParser.cs` : parser state to track tag parsing
- `compiler/InkParser/InkParser_Tags.cs` : new parse predicates : 
   - `StartTag` replaces `Tag`
   - `EndTagIfNecessary` (2 signatures), 
   - `EndChoiceTagIfNecessary`
- Implement new `EndChoiceTagIfNecessary` parse predicate in :
   - `compiler/InkParser/InkParser_Choices.cs`
   - `compiler/InkParser/InkParser_Content.cs`
   - `compiler/InkParser/InkParser_Divert.cs`
- Implement new `EndTagIfNecessary` parse predicate in :  
   - `compiler/InkParser/InkParser_Logic.cs`
- compiler/ParsedHierarchy/Tag.cs : Tag is now a full Parsed Object (older Tag is renamed LegacyTag in `compiler/ParsedHierarchy/TunnelOnwards.cs`)

**Compiler : Variable diverts**
- `compiler/ParsedHierarchy/TunnelOnwards.cs`  : Allow passing a variable divert to tunnel onward

**Compiler : Plugins**
- New plugins logic

**Runtime : Tags**
- `ink-engine-runtime/Choice.cs` : expose `tags` property
- `ink-engine-runtime/ControlCommand.cs` : 3 new `ControlCommand`s
- `ink-engine-runtime/JsonSerialisation.cs` : serialize new `ControlCommand`s
- `ink-engine-runtime/Story.cs` : 
   - new method `PopChoiceStringAndTags`
   - implement it in `ProcessChoice`
   - implement new `ControlCommand`s
   - handle new Tag in the hierarchy of containers
 - `ink-engine-runtime/StoryState.cs`
    - handle tags in `currentText`
    - expose and handle tags in `CleanOutputWhitespace`

**Engine : Misc**
- `ink-engine-runtime/Story.cs` 
   - bump `inkVersion` to 21
   - bump `kInkSaveStateVersion` to 10
   - shortcuts for `currentFlowIsDefaultFlow` and `aliveFlowNames`
- `ink-engine-runtime/StoryState.cs`
   - 2 new methods/property : `currentFlowIsDefaultFlow` and `_aliveFlowNames`
   - accept `booleans` as argument of `EvaluateFunction / ChoosePathStringWithParameters`
- `ink-engine-runtime/InkList.cs` : bug at copy already ported by @joningold (to be verified)
   - 2 new utils methods : `HasIntersection`, `Contains` (with string argument)
   - 1 breaking change in `Contains` (testing Contains with empty lists is now falsy)
 

**Tests**
- `tests/Tests.cs` :
   - `TestContainsEmptyListAlwaysFalse`
   - `TestTunnelOnwardsToVariableDivertTarget`
   - `TestTagsInSeq`
   - `TestTagsInChoice`
   - `TestTagsDynamicContent`

As usual any help is more than welcome !  
I myself will probably start porting the tests first so that we can have a failing build and be happy when it actually passes !

**Comment by smwhr** [comment]
I suggest 
- 1 runtime branch to get the new features playable out there
- 1 compiler branch that can be released later (it's not like many people use the js compiler anyway)

**Comment by ephread** [comment]
Wow, you've already listed the changes, awesome work! Seems that there are A LOT more changes on the compiler side of things.

Let's create the `runtime-v1.1` & `compiler-v1.1` branches and track what has been implemented / not implemented in the related PRs then, like #846.

**Comment by smwhr** [comment]
Branch created 
- PR with the new Tests posted
- PR with fix and port of InkList posted

I'll quickly do
- `ink-engine-runtime/ControlCommand.cs`
- `ink-engine-runtime/JsonSerialisation.cs`

and then off to bed :)

**Comment by smwhr** [comment]
Everything is in https://github.com/y-lohse/inkjs/pull/985 and open for review.
All tests pass :)
