### ISSUE TITLE
[Help] How to use `PosixFileHandler` in conjunction with Webpack 5

### ISSUE THREAD

**Issue by ndekross** [y-lohse/inkjs#989]
I'm trying to include additional files with the main ink file, as follows:

```ink
INCLUDE additional.ink
```
But the compiler requires a file handler for that. With Webpack 5 I import the ink files as assets and directly pass the ink files to the compiler in in my `index.js`, as follows: 

```js
import Story from 'story.ink'
import { Compiler } from 'inkjs'

const story = new Compiler(Story).Compiler()
```
I see that there is a file handler included with the `inkjs` package. So I tried to do the following:

```js
import Story from 'story.ink'
import { Compiler } from 'inkjs'
import { PosixFileHandler } from 'inkjs/compiler/FileHandler/PosixFileHandler'

const fileHandler = new PosixFileHandler(".")
const story = new Compiler(Story, { fileHandler }).Compiler()
```
But that doesn't work because `PosixFileHandler` uses built-in Node modules and I'm not sure how to include them with webpack. What's a good way to handle ink includes with Webpack and in-browser compilation?

**Comment by smwhr** [comment]
Hello, you cannot use the `PosixFileHandler` in browser (because the browser does not know how to read files or even know what a filesystem is.).

You should use the `JsonFileHandler` instead : 

```javascript
const fileHandler = new JsonFileHandler({
    "additional.ink": "The content of additional.ink",
  "somefolder/another.ink": "The content of a second file that is inside somefolder."
})
```

You can access `fileHandler. fileHierarchy` after initialization if you want to modify the filehandler.

**Comment by smwhr** [comment]
Note that you can also implement your own that does more tricky things, you just have to implement the interface : https://github.com/y-lohse/inkjs/blob/master/src/compiler/IFileHandler.ts
