### ISSUE TITLE
Compile crash

### ISSUE THREAD

**Issue by tuoxiansp** [y-lohse/inkjs#994]
## Describe the bug
compile ink script failed;
error msg: `Error: Compilation failed.`

## Ink script
```
+ 1 #[2] #[3]
```

## To Reproduce
https://runkit.com/tuoxiansp/runkit-npm-inkjs

## Environment
 - _inkjs_ version: v2.2.0

**Comment by smwhr** [comment]
It does not work in inky either : the syntax is _truly_ incorrect here.
